import { chromium } from "playwright";
import { readFileSync, existsSync } from "fs";
import path from "path";
const exe = ["/opt/pw-browsers/chromium-1194/chrome-linux/chrome"].find(existsSync);
const state = readFileSync("seed-state.json", "utf8");
const b = await chromium.launch({ executablePath: exe, args: ["--no-sandbox"] });
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
const errs=[]; p.on("pageerror",e=>errs.push(e.message));
await p.addInitScript((s)=>{const m=new Map();m.set("scp:stato:v1",s);window.storage={async get(k){return m.has(k)?{value:m.get(k)}:null},async set(k,v){m.set(k,v);return true},async delete(k){m.delete(k);return true}};},state);
await p.goto("file://"+path.resolve("index.html")); await p.waitForTimeout(1400);
await p.getByText("Admin",{exact:false}).first().click(); await p.waitForTimeout(400);
for(const d of "1234") await p.getByRole("button",{name:d,exact:true}).first().click().catch(()=>{});
await p.waitForTimeout(1000);
await p.getByText("Catalogo",{exact:true}).first().click(); await p.waitForTimeout(400);
await p.getByText("Prodotti ·",{exact:false}).first().click().catch(()=>{}); await p.waitForTimeout(400);
await p.getByRole("button",{name:"Modifica Patate forno"}).click(); await p.waitForTimeout(700);
const has = await p.getByText("Prezzo d'acquisto",{exact:false}).count();
console.log("price field present:", has>0);
await p.screenshot({path:"t-form-open.png"});
console.log("pageerrors:", errs.length, errs.slice(0,3));
await b.close();
