import { chromium } from "playwright";
import { readFileSync, existsSync } from "fs";
import path from "path";
import { vaiA } from "./navtest.mjs";
const exe = ["/opt/pw-browsers/chromium-1194/chrome-linux/chrome"].find(existsSync);
const st = JSON.parse(readFileSync("seed-state.json", "utf8"));
const mag = st.magazzini.find((m) => m.articoli.length >= 2);
const b = await chromium.launch({ executablePath: exe, args: ["--no-sandbox"] });
const p = await b.newPage({ viewport: { width: 1200, height: 950 } });
await p.addInitScript((s) => { try { localStorage.setItem("scp:tour:v1","1"); } catch {} const m = new Map(); m.set("scp:stato:v1", s); window.storage = { async get(k){return m.has(k)?{value:m.get(k)}:null}, async set(k,v){m.set(k,v);return true}, async delete(k){m.delete(k);return true} }; }, JSON.stringify(st));
await p.goto("file://" + path.resolve("index.html")); await p.waitForTimeout(1500);
await p.getByText("Admin", { exact: false }).first().click(); await p.waitForTimeout(400);
for (const d of "1234") await p.getByRole("button", { name: d, exact: true }).first().click().catch(()=>{});
await p.waitForTimeout(1200);
await vaiA(p, "Magazzini");
console.log("magazzino cercato:", mag.nome);
const carte = await p.getByText(mag.nome, { exact: false }).locator("visible=true").count();
console.log("quante volte si vede il nome:", carte);
for (let i = 0; i < carte; i++) { const t = await p.getByText(mag.nome, { exact: false }).locator("visible=true").nth(i).evaluate((e) => e.tagName + "|" + (e.closest("button") ? "dentro-un-tasto" : "no-tasto") + "|" + e.textContent.slice(0,40)); console.log("  ", i, t); } await p.waitForTimeout(800);
const dopo = await p.locator("h1, h2").allInnerTexts(); console.log("titoli:", JSON.stringify(dopo.slice(0,4)));
console.log("«Gestione rapida»:", await p.getByRole("button", { name: /Gestione rapida/ }).count());
const btns = await p.getByRole("button").allInnerTexts();
console.log("tasti visibili dopo Gestione rapida:");
for (const t of btns.map(x=>x.replace(/\s+/g," ").trim()).filter(Boolean).slice(0,25)) console.log("   ·", t.slice(0,70));
await p.screenshot({ path: "sonda-b2.png", fullPage: true });
await b.close();
