-- gen617: 27 zone cambiate, 55 tessere
-- cf97cfd7ced5c37f3d7d468d9486d5bb (988312) → f96ad21282fa8f09b48696aa3f0ba5a9 (997686)

insert into kv_store(key, value) select 'backup:pre-gen617', value from kv_store where key='app:jsx:src'
  on conflict (key) do update set value=excluded.value;

insert into kv_store(key, value) values('tmp:gen617:p001', substr((select value from kv_store where key='app:jsx:src'), 1, 40780)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p002', convert_from(decode('Y29uc3QgVkVSU0lPTkUgPSAiZ2VuLTYuMTciOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p003', substr((select value from kv_store where key='app:jsx:src'), 40810, 24564)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p004', convert_from(decode('Lyog4pSA4pSAIExBIENBVEVHT1JJQSBERUxMJ0FHR0lVTlRBIFNJIExFR0dFIERBTCBNQUdBWlpJTk8gKGdlbi02LjE3KSDilIDilIAKICAgUGFyb2xlIGRpIFZhbGVyaW86IMKrbGUgYWdnaXVudGUgc29ubyBzZW1wcmUgZ2xpIGluZ3JlZGllbnRpIHByZXNlbnRpIG5lbAogICBtYWdhenppbm8gbyBmcmlnbyBjb24gaSBxdWFsaSBzaSBwcmVwYXJhbm8gbGUgcGlldGFuemUsIHF1aW5kaSBub24gZG92cmVpCiAgIG5lYW5jaGUgcmlzY3JpdmVybGUgZSBjYXRlZ29yaXp6YXJsZSBwZXJjaGUnIGwnaG8gZ2lhJyBmYXR0b8K7LgogICBIYSByYWdpb25lOiBsYSBjYXRlZ29yaWEgYydlJyBnaWEnLCBzdGEgc3VsIFBST0RPVFRPIGRlbCBjYXRhbG9nby4gU2UKICAgbCdhZ2dpdW50YSBoYSB1bmEgZGlzdGludGEsIGxhIHN1YSBjYXRlZ29yaWEgc2kgZGVkdWNlIGRhIGxpJy4KICAgUVVFTExBIFNDUklUVEEgQSBNQU5PIFZJTkNFLCBzZW1wcmU6IGUnIHVuYSBzY2VsdGEgZXNwbGljaXRhIGRpIGNoaSBzdGEgYWwKICAgYmFuY28sIGxhIGRpc3RpbnRhIGUnIGlsIHJpcGllZ28uIElsIGNvbnRyYXJpbyBidXR0ZXJlYmJlIHZpYSBpbCBsYXZvcm8gZGkKICAgY2hpIGwnaGEgc2NyaXR0YSDigJQgZWQgZScgaWwgbW90aXZvIHBlciBjdWkgaWwgY2FtcG8gbGliZXJvIHJlc3RhLgogICBTaSBmZXJtYSBhbCBQUklNTyBwcm9kb3R0byBjaGUgdW5hIGNhdGVnb3JpYSBjZSBsJ2hhOiB1bmEgZGlzdGludGEgZGkKICAgZmFyaW5hICsgbW96emFyZWxsYSArIHNhbGUgbm9uIGhhIMKrdW5hwrsgY2F0ZWdvcmlhLCBlIGludmVudGFybmUgdW5hIG1lZGlhCiAgIHNhcmViYmUgcGVnZ2lvIGNoZSBkaXJlIMKrQWx0cm/Cuy4KICAgU3RyaW5nYSB2dW90YSA9IG5lc3N1bmE6IGNoaSBjaGlhbWEgZGVjaWRlIHNlIGRpdmVudGEgwqtBbHRyb8K7LiAqLwpjb25zdCBjYXRlZ29yaWFBZ2cgPSAoc3RhdG8sIGEpID0+IHsKICBjb25zdCBzY3JpdHRhID0gKGE/LmNhdGVnb3JpYSB8fCAiIikudHJpbSgpOwogIGlmIChzY3JpdHRhKSByZXR1cm4gc2NyaXR0YTsKICBmb3IgKGNvbnN0IGQgb2YgYT8uZGlzdGludGEgfHwgW10pIHsKICAgIGNvbnN0IHByb2QgPSB0cm92YShzdGF0by5wcm9kb3R0aSB8fCBbXSwgZC5wcm9kb3R0b0lkKTsKICAgIGNvbnN0IGNhdCA9IHByb2QgJiYgdHJvdmEoc3RhdG8uY2F0ZWdvcmllIHx8IFtdLCBwcm9kLmNhdGVnb3JpYUlkKTsKICAgIGNvbnN0IG5vbWUgPSAoY2F0Py5ub21lIHx8ICIiKS50cmltKCk7CiAgICBpZiAobm9tZSkgcmV0dXJuIG5vbWU7CiAgfQogIHJldHVybiAiIjsKfTsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p005', substr((select value from kv_store where key='app:jsx:src'), 65374, 94452)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p006', convert_from(decode('Lyog4pSA4pSAIENISSBTVEEgU09MTyBJTiBDQVNTQSAoZ2VuLTYuMTcsIHBhcm9sZSBkaSBWYWxlcmlvIGRlbCAxMyBzZXR0ZW1icmU6CiAgICAgwqtsYSBjYXNzYSBhbmNvcmEgdmVkZSBsZSBhbHRyZSBzZXppb25pIGNoZSBub24gbGUgaW50ZXJlc3Nhbm/CuyBlIMKrbGEKICAgICBjYXNzYSBwdW8nIHNvbG8gdXRpbGl6emFyZSBsZSBmdW56aW9uYWxpdGEnIGRlbGxhIGNhc3NhwrspIOKUgOKUgAogICBFJyB1biBJTlRFUlJVVFRPUkUsIG5vbiB1bmEgZGVkdXppb25lLiBMYSB0ZW50YXppb25lIGVyYSBzY3JpdmVybG8gY29tZQogICDCq2hhIGNhc3NhIGUgbm9uIGhhIG5lJyBjb3JyZXppb25pIG5lJyBzdHJ1dHR1cmHCuzogc2VtYnJhIGdyYXRpcyBwZXJjaGUnCiAgIG9nZ2kgZGVzY3JpdmUgZXNhdHRhbWVudGUgbCd1bmljbyBwcm9maWxvIGRpIGNhc3NhIGNoZSBlc2lzdGUuIE1hIHNhcmViYmUKICAgdW5hIHJlZ29sYSBkZWRvdHRhIGRhIHVuJ0FTU0VOWkEsIGUgaWwgZ2lvcm5vIGNoZSB1biBhZG1pbiBhc3NlZ25hIHVuYQogICBsaW5lYSBhbCBjYXNzaWVyZSDigJQgbyBhY2NlbmRlIMKrY2Fzc2HCuyBhIHVuIG1hZ2F6emluaWVyZSDigJQgcXVlbGxhIHBlcnNvbmEKICAgc2kgdHJvdmVyZWJiZSBzZW56YSBDb250ZWdnaSBzZW56YSBjaGUgbmVzc3VubyBhYmJpYSBzcGVudG8gbmllbnRlLgogICBRdWkgc3RydXR0dXJhLCBjb3JyZXppb25pLCBvcmRpbmkgZSBjYXNzYSBzb25vIFRVVFRJIGludGVycnV0dG9yaQogICBlc3BsaWNpdGk6IGwnYWRtaW4gZGVjaWRlLCBsJ2FwcCBub24gaW5kb3ZpbmEuIFF1ZXN0byBlJyBpbCBxdWludG8uCiAgIFByZXRlbmRlIMKrY2Fzc2HCuzogdW5hIGJhcnJhIGZhdHRhIGRpIHNvbGUgdm9jaSBkZWxsYSBDYXNzYSwgYWRkb3NzbyBhIGNoaQogICBpbiBDYXNzYSBub24gcHVvJyBlbnRyYXJlLCBzYXJlYmJlIHVuYSBwb3J0YSBzdSB1biBtdXJvLiAqLwpmdW5jdGlvbiBzb2xvQ2Fzc2EocHJvZmlsbykgewogIHJldHVybiBwcm9maWxvPy5ydW9sbyAhPT0gImFkbWluIiAmJiAhIXByb2ZpbG8/LnNvbG9DYXNzYSAmJiBwdW9DYXNzYShwcm9maWxvKTsKfQo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p007', substr((select value from kv_store where key='app:jsx:src'), 159826, 102698)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p008', convert_from(decode('ICAvKiBzaSBjYWxjb2xhIG5lbCBDT1JQTywgYSBvZ25pIHJlbmRlciwgZSBub24gaW4gdW5vIHN0YXRvOiDCq3Byb2ZpbG/CuyBlJwogICAgIGRlcml2YXRvIGRhIHN0YXRvLnByb2ZpbGkgZWQgZScgdml2bywgcXVpbmRpIHVuIHBlcm1lc3NvIGFjY2VzbyBvIHNwZW50bwogICAgIGRhbGwnYWRtaW4gYXJyaXZhIGFsIHBvbGwgZG9wbyBzZW56YSBjaGUgbmVzc3VubyByaWNhcmljaGkgbmllbnRlLiAqLwogIGNvbnN0IHNvbG9RdWkgPSBzb2xvQ2Fzc2EocHJvZmlsbyk7CiAgY29uc3QgW3Zpc3RhLCBzZXRWaXN0YV0gPSB1c2VTdGF0ZShzb2xvUXVpID8gImNhc3NhIiA6ICJob21lIik7Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p009', substr((select value from kv_store where key='app:jsx:src'), 262570, 2219)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p010', convert_from(decode('ICAvKiDilIDilIAgTEUgVFJFIFZPQ0kgREVMTEEgQ0FTU0EgTkFWSUdBTk8gKGdlbi02LjE3KSDilIDilIAKICAgICBGaW5vIGEgaWVyaSBjaGlhbWF2YW5vIHNvbG8gc2V0U2V6Q2Fzc2EsIGUgYmFzdGF2YTogbGEgYmFycmEgZGVsbGEgQ2Fzc2EKICAgICBlc2lzdGV2YSBzb2xvIERFTlRSTyBsYSBDYXNzYSwgcXVpbmRpIMKrdmlzdGHCuyBlcmEgZ2lhJyBnaXVzdGEuIERhIG9nZ2kKICAgICBwZXIgY2hpIHN0YSBzb2xvIGluIGNhc3NhIHF1ZWxsYSBiYXJyYSBlJyBsJ3VuaWNhIGNoZSBoYSwgZSB1bmEgdm9jZSBjaGUKICAgICBzaSBhY2NlbmRlIHNlbnphIHBvcnRhcmUgZGEgbmVzc3VuYSBwYXJ0ZSBlJyBlc2F0dGFtZW50ZSBsYSDCq3BvcnRhIGNoZQogICAgIG5vbiBhcHJlIG5pZW50ZcK7IGNoZSBxdWVzdGEgY2FzYSB2aWV0YS4gTm9uIHBhc3NhIGRhIG5hdmlnYSgpIHBlcmNoZScKICAgICBuYXZpZ2EoImNhc3NhIikgcmltZXR0ZSBzZW1wcmUgwqtiYXR0ZXJlwrssIGUgbWFuZ2VyZWJiZSBsYSBzZXppb25lCiAgICAgY2hpZXN0YSBwcm9wcmlvIGRhIGNoaSBsJ2hhIGNoaWVzdGEuICovCiAgY29uc3QgdmFpSW5DYXNzYSA9IChzKSA9PiB7IHNldFNhbHRvKG51bGwpOyBzZXRWaXN0YSgiY2Fzc2EiKTsgc2V0U2V6Q2Fzc2Eocyk7IH07Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p011', substr((select value from kv_store where key='app:jsx:src'), 264789, 1591)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p012', convert_from(decode('ICAvKiDilIDilIAgTEEgQkFSUkEgREVMTEEgQ0FTU0EsIFNDUklUVEEgVU5BIFZPTFRBIFNPTEEgKGdlbi02LjE3KSDilIDilIAKICAgICBMYSB1c2FubyBpbiBkdWU6IGNoaSBzdGEgc29sbyBpbiBjYXNzYSAoZScgbGEgc3VhIGJhcnJhLCBzZW1wcmUpIGUKICAgICBjaGl1bnF1ZSBhbHRybyBlbnRyaSBpbiBDYXNzYSAoY2UgbCdoYSBmaW5jaGUnIHJlc3RhIGxpJykuIFNjcml2ZXJsYSBkdWUKICAgICB2b2x0ZSB2b3JyZWJiZSBkaXJlIGNoZSBsYSBwcm9zc2ltYSBtb2RpZmljYSBuZSBjYW1iaWEgdW5hIHNvbGEuCiAgICAgVFJFIFZPQ0kgcGVyIGNoaSBzdGEgc29sbyBpbiBjYXNzYSwgUVVBVFRSTyBwZXIgZ2xpIGFsdHJpLCBlIGxhCiAgICAgZGlmZmVyZW56YSBlJyDCq0VzY2nCuy4gUGVyIGdsaSBhbHRyaSDCq0VzY2nCuyByaXBvcnRhIGEgSG9tZSwgY2hlIGUnIHVuYQogICAgIHN0YW56YSBjaGUgaGFubm8uIENoaSBzdGEgc29sbyBpbiBjYXNzYSB1bmEgSG9tZSBub24gY2UgbCdoYTogbGEgc3VhCiAgICAgdXNjaXRhIGUnIGlsIGJvdHRvbmUgY2hlIHN0YSBHSUEnIGluIGludGVzdGF6aW9uZSwgY29sbGF1ZGF0byBkYSBzZW1wcmUuCiAgICAgVW5hIHF1YXJ0YSB2b2NlIMKrRXNjaSBkYWwgcHJvZmlsb8K7IHF1aSBzb3R0byBzYXJlYmJlIGR1ZSBib3R0b25pIGNvbiBsbwogICAgIHN0ZXNzbyBub21lIHN1bGxhIHN0ZXNzYSBzY2hlcm1hdGEg4oCUIHVuYSB0cmFwcG9sYSBwZXIgY2hpIGxlZ2dlLCBlIHBlciBpCiAgICAgYmFuY2hpIGNoZSBsbyBjZXJjYW5vIHBlciBub21lIOKAlCBlIGEgMzYwcHggc2kgdHJvbmNoZXJlYmJlOiBsYSBiYXJyYSBkYScKICAgICA4MXB4IGEgdm9jZSwgZSBzZWRpY2kgY2FyYXR0ZXJpIGluIGdyYXNzZXR0byBkYSAxMCw1cHggbmUgY2hpZWRvbm8gZGkKICAgICBwaXUnLiBMZSBpY29uZSBzb25vIGZyYSBxdWVsbGUgZ2lhJyBpbXBvcnRhdGUuICovCiAgY29uc3QgQkFSUkFfQ0FTU0EgPSBbCiAgICB7IGlkOiAiY2Fzc2EtYmF0dGVyZSIsIG5vbWU6ICJCYXR0ZXJlIiwgaWNvbmE6IFN0b3JlLCBwcm9udGE6IHRydWUsCiAgICAgIGF0dGl2YTogdmlzdGEgPT09ICJjYXNzYSIgJiYgc2V6Q2Fzc2EgPT09ICJiYXR0ZXJlIiwgYXppb25lOiAoKSA9PiB2YWlJbkNhc3NhKCJiYXR0ZXJlIikgfSwKICAgIHsgaWQ6ICJjYXNzYS1jbGllbnRpIiwgbm9tZTogIkNsaWVudGkiLCBpY29uYTogVXNlcnMsIHByb250YTogdHJ1ZSwKICAgICAgYXR0aXZhOiB2aXN0YSA9PT0gImNhc3NhIiAmJiBzZXpDYXNzYSA9PT0gImNsaWVudGkiLCBhemlvbmU6ICgpID0+IHZhaUluQ2Fzc2EoImNsaWVudGkiKSB9LAogICAgeyBpZDogImNhc3NhLWdpb3JuYXRhIiwgbm9tZTogIkdpb3JuYXRhIiwgaWNvbmE6IEJhckNoYXJ0MywgcHJvbnRhOiB0cnVlLAogICAgICBhdHRpdmE6IHZpc3RhID09PSAiY2Fzc2EiICYmIHNlekNhc3NhID09PSAiZ2lvcm5hdGEiLCBhemlvbmU6ICgpID0+IHZhaUluQ2Fzc2EoImdpb3JuYXRhIikgfSwKICAgIC4uLihzb2xvUXVpID8gW10gOiBbeyBpZDogImNhc3NhLWVzY2kiLCBub21lOiAiRXNjaSIsIGljb25hOiBBcnJvd0xlZnQsIHByb250YTogdHJ1ZSwKICAgICAgYXR0aXZhOiBmYWxzZSwgYXppb25lOiAoKSA9PiBuYXZpZ2EoImhvbWUiKSB9XSksCiAgXTsKICBjb25zdCBOQVYgPSBzb2xvUXVpID8gQkFSUkFfQ0FTU0EgOiB7Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p013', substr((select value from kv_store where key='app:jsx:src'), 266396, 2789)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p014', convert_from(decode('ICAvKiBEZW50cm8gbGEgQ2Fzc2EgbGEgYmFycmEgZScgcXVlbGxhIGRlbGxhIENhc3NhOiBub24gc2kgdG9nbGllIG5pZW50ZSBhCiAgICAgbmVzc3Vubywgc2kgY2FtYmlhIHN0YW56YSwgZSBsYSBwb3J0YSBkaSByaXRvcm5vIGUnIHNlbXByZSBsbyBzdGVzc28KICAgICB0YXN0byBuZWxsbyBzdGVzc28gcG9zdG8uIFBlciBjaGkgc3RhIHNvbG8gaW4gY2Fzc2EgZScgbGEgYmFycmEgZGkKICAgICBzZW1wcmUsIGFuY2hlIG5lbGxhIHNjaGVybWF0YSBjaGUgZGljZSBjaGUgdW5hIHNlemlvbmUgbm9uIGUnIHN1YSDigJQKICAgICBjb3NpJyBkYSBsaScgc2kgdG9ybmEgYSBiYXR0ZXJlIGNvbiB1biB0b2NjbyBpbnZlY2UgY2hlIGNvbCBsb2dvdXQuICovCiAgY29uc3QgTkFWX1FVSSA9IChzb2xvUXVpIHx8IHZpc3RhID09PSAiY2Fzc2EiKSA/IEJBUlJBX0NBU1NBIDogTkFWOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p015', substr((select value from kv_store where key='app:jsx:src'), 270272, 431)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p016', convert_from(decode('ICAgICAgLyogYSBjaGkgc3RhIHNvbG8gaW4gY2Fzc2EgTk9OIHBhcnRlOiBsYSBwYW5vcmFtaWNhIHJhY2NvbnRhIENvbnRhIMK3CiAgICAgICAgIE9yZGluYSDCtyBSaWNldmksIGNoZSBlJyBpbCBtZXN0aWVyZSBkaSB1biBhbHRyby4gTGEgY2hpYXZlIHNpIHNjcml2ZQogICAgICAgICBsbyBzdGVzc28sIGNvc2knIHNlIHVuIGdpb3JubyBjYW1iaWEgbWVzdGllcmUgbm9uIGdsaSBwYXJ0ZSBhZGRvc3NvCiAgICAgICAgIHVuIGdpcm8gdmVjY2hpbyAoZ2VuLTYuMTcpLiAqLwogICAgICBpZiAoIXNvbG9RdWkgJiYgIWxvY2FsU3RvcmFnZS5nZXRJdGVtKGspICYmICFsb2NhbFN0b3JhZ2UuZ2V0SXRlbSgic2NwOnRvdXI6djEiKSkgc2V0R3VpZGEocGFzc2lQYW5vcmFtaWNhKE5BVikpOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p017', substr((select value from kv_store where key='app:jsx:src'), 270811, 2291)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p018', convert_from(decode('ICAgICAgLyogY2hpIHN0YSBzb2xvIGluIGNhc3NhIGhhIHVuYSBzdGFuemEgc29sYS4gTGEgbGVudGUgZSBpbCDCqz/CuyBzb25vIGdpYScKICAgICAgICAgZmlsdHJhdGk7IHF1ZXN0byBlJyBpbCBtdXJvIGRpIHJpc2VydmEsIGNoZSB2YWxlIGFuY2hlIHBlciBsZSBwb3J0ZQogICAgICAgICBkaSBkb21hbmkg4oCUIGxhIHN0ZXNzYSByYWdpb25lIHBlciBjdWkgaWwgZ2F0ZSBlc2lzdGUgKGdlbi01Ljk1KS4gKi8KICAgICAgKHNvbG9RdWkgJiYgdmlzdGEgIT09ICJjYXNzYSIpIHx8Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p019', substr((select value from kv_store where key='app:jsx:src'), 273102, 9737)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p020', convert_from(decode('ICAgICAgICAgIHsvKiBhIGNoaSBzdGEgc29sbyBpbiBjYXNzYSBxdWVzdGUgZHVlIG5vbiBzaSBvZmZyb25vOiBsYSBQbGFuY2lhCiAgICAgICAgICAgICAgZScgdW5hIHBvcnRhIGNoZSBpbCBnYXRlIHF1aSBzb3ByYSBnbGkgY2hpdWRlLCBlIGxhIFBhbm9yYW1pY2EKICAgICAgICAgICAgICByYWNjb250YSB1biBtZXN0aWVyZSBjaGUgbm9uIGUnIGlsIHN1by4gR2xpIHJlc3RhIGxhIGd1aWRhCiAgICAgICAgICAgICAgZGVsbGEgc3VhIHN0YW56YSwgY2hlIGVzY2UgY29sIG5vbWUgZ2l1c3RvIGdyYXppZSBhCiAgICAgICAgICAgICAgRlVPUklfQkFSUkEgKGdlbi02LjE3KS4gKi99CiAgICAgICAgICB7IXNvbG9RdWkgJiYgKDw+Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p021', substr((select value from kv_store where key='app:jsx:src'), 282839, 1441)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p022', convert_from(decode('ICAgICAgICAgIDwvPil9Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p023', substr((select value from kv_store where key='app:jsx:src'), 284280, 52872)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p024', convert_from(decode('ICAgIC8qIGNoaSBzdGEgc29sbyBpbiBjYXNzYSBoYSBVTkEgcG9ydGEsIGUgbGEgbGVudGUgbm9uIGdsaWVuZSBhcHJlIGFsdHJlOgogICAgICAgaSBmaWx0cmkgcXVpIHNvdHRvIGNvcHJvbm8gY2F0YWxvZ28sIGNvbnRlZ2dpLCBwbGFuY2lhLCBjYXNzYSBlIGdsaQogICAgICAgb3JkaW5pIGNvbiDCq3NlcnZlwrssIG1hIE5PTiBpIG1hZ2F6emluaSAoY2kgYXJyaXZhbm8gcGVyIGlsIHJpcGllZ28KICAgICAgIGZpbmFsZSksIE5PTiBsZSBjb21hbmRlICh0cnVlIHBlciB0dXR0aSwgYXBwb3N0YSkgZSBOT04gbGUgdm9jaSBkZWdsaQogICAgICAgb3JkaW5pIHNlbnphIMKrc2VydmXCuy4gQ29uIGxhIGJhcnJhIGRlbGxhIENhc3NhIGZpc3NhLCBvZ251bmEgZGkgcXVlbGxlCiAgICAgICBwb3J0ZSBsbyBsYXNjZXJlYmJlIGluIHVuYSBzdGFuemEgY2hlIG5vbiBlJyBzdWEgKGdlbi02LjE3KS4gKi8KICAgIGlmIChzb2xvQ2Fzc2EocHJvZmlsbykpIHJldHVybiBhLmQgPT09ICJjYXNzYSI7Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p025', substr((select value from kv_store where key='app:jsx:src'), 337152, 1027)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p026', convert_from(decode('ICAvKiBlIG5lbW1lbm8gbGUgcmlnaGUgZGVpIHByb2RvdHRpOiBvZ251bmEgcG9ydGEgdW4gYm90dG9uZSBjaGUgYXByZSBpCiAgICAgTWFnYXp6aW5pLCBlIHVuIGNhc3NpZXJlIG5vbiBoYSBkb21hbmRlIGRpIG1hZ2F6emlubyAoZ2VuLTYuMTcpICovCiAgaWYgKHNvbG9DYXNzYShwcm9maWxvKSkgcmV0dXJuIFtdOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p027', substr((select value from kv_store where key='app:jsx:src'), 338179, 99890)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p028', convert_from(decode('ICBjb25zdCBbc29sb0JhbmNvLCBzZXRTb2xvQmFuY29dID0gdXNlU3RhdGUoISFpdGVtPy5zb2xvQ2Fzc2EpOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p029', substr((select value from kv_store where key='app:jsx:src'), 438069, 2883)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p030', convert_from(decode('ICAgICAgICAvKiBhcHBlc28gYSDCq2Nhc3Nhwrs6IHNlIGxhIGNhc3NhIHNpIHNwZWduZSwgc2kgc3BlZ25lIGFuY2hlIHF1ZXN0byDigJQKICAgICAgICAgICB1bmEgYmFycmEgZGkgc29sZSB2b2NpIGRlbGxhIENhc3NhIGFkZG9zc28gYSBjaGkgaW4gQ2Fzc2Egbm9uIHB1bycKICAgICAgICAgICBlbnRyYXJlIHNhcmViYmUgdW5hIHBvcnRhIHN1IHVuIG11cm8gKGdlbi02LjE3KSAqLwogICAgICAgIHNvbG9DYXNzYTogcnVvbG8gPT09ICJhZG1pbiIgPyB1bmRlZmluZWQgOiAoKGNhc3NhICYmIHNvbG9CYW5jbykgfHwgdW5kZWZpbmVkKSwK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p031', substr((select value from kv_store where key='app:jsx:src'), 440952, 6359)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p032', convert_from(decode('ICAgICAgICAgIHsvKiBjb21wYXJlIHNvbG8gc2UgbGEgY2Fzc2EgZScgYWNjZXNhOiBzZW56YSwgc2FyZWJiZSB1bgogICAgICAgICAgICAgIGludGVycnV0dG9yZSBjaGUgbm9uIHB1bycgZmFyZSBuaWVudGUgKGdlbi02LjE3KSAqL30KICAgICAgICAgIHtjYXNzYSAmJiAoCiAgICAgICAgICAgIDxJbnRlcnJ1dHRvcmVBdXQgYWNjZXNvPXtzb2xvQmFuY299IG9uQ2FtYmlhPXsoKSA9PiBzZXRTb2xvQmFuY28oKHYpID0+ICF2KX0KICAgICAgICAgICAgICB0aXRvbG89IlN0YSBzb2xvIGluIGNhc3NhIgogICAgICAgICAgICAgIHNvdHRvPSJDaGkgbG8gaGEgYWNjZXNvIGFwcmUgbCdhcHAgZGlyZXR0YW1lbnRlIHN1bGxhIENhc3NhIGUgc290dG8gaWwgcG9sbGljZSB0cm92YSBCYXR0ZXJlIMK3IENsaWVudGkgwrcgR2lvcm5hdGEsIG5pZW50ZSBhbHRybzogbsOpIGNvbnRlZ2dpLCBuw6kgbWFnYXp6aW5pLCBuw6kgb3JkaW5pLiBTaSBlc2NlIGRhbCBwcm9maWxvIGNvbCB0YXN0byBpbiBhbHRvIGEgZGVzdHJhLiBBY2NlbmRpbG8gcGVyIGNoaSBhbCBiYW5jbyBiYXR0ZSBlIGJhc3RhLiIgLz4KICAgICAgICAgICl9Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p033', substr((select value from kv_store where key='app:jsx:src'), 447311, 311529)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p034', convert_from(decode('ICAgICAgICAgIChjYXRlZ29yaWFBZ2coc3RhdG8sIGEpIHx8ICJcdWZmZmYiKS5sb2NhbGVDb21wYXJlKGNhdGVnb3JpYUFnZyhzdGF0bywgYikgfHwgIlx1ZmZmZiIsICJpdCIpCg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p035', substr((select value from kv_store where key='app:jsx:src'), 758951, 374)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p036', convert_from(decode('ICAgICAgICAgICAgICAgIHtjYXRlZ29yaWFBZ2coc3RhdG8sIGFnKSA/IGAke2NhdGVnb3JpYUFnZyhzdGF0bywgYWcpfSDCtyBgIDogIiJ9e2ZtdEV1cm8oYWcucHJlenpvIHx8IDApfSDCtyB7KGFnLmdydXBwaSB8fCBbXSkuam9pbigiLCAiKSB8fCAibmVzc3VuIGdydXBwbyJ9Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p037', substr((select value from kv_store where key='app:jsx:src'), 759461, 14351)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p038', convert_from(decode('ICAgICAgICAgIHN1Z2dlcmltZW50bz0iUmFnZ3J1cHBhIGdsaSBpbmdyZWRpZW50aSBuZWxsYSBmYXNjaWEgZGVsbGEgQ2Fzc2EuIFNpIHB1w7IgbGFzY2lhcmUgdnVvdGE6IGxhIHByZW5kZSBkYWwgcHJvZG90dG8gZGVsbGEgZGlzdGludGEsIGUgc2Ugbm9uIGMnw6ggbmVtbWVubyBxdWVsbG8gZmluaXNjZSBzb3R0byDCq0FsdHJvwrsuIiAvPgogICAgICAgIHsvKiDilIDilIAgUVVFTExPIENIRSBOT04gU0VSVkUgUklTQ1JJVkVSRSAoZ2VuLTYuMTcpIOKUgOKUgAogICAgICAgICAgICBQYXJvbGUgZGkgVmFsZXJpbzogwqtub24gZG92cmVpIG5lYW5jaGUgcmlzY3JpdmVybGUgZQogICAgICAgICAgICBjYXRlZ29yaXp6YXJsZSBwZXJjaGUnIGwnaG8gZ2lhJyBmYXR0b8K7LiBTZSBsYSBkaXN0aW50YSBwdW50YSBhIHVuCiAgICAgICAgICAgIHByb2RvdHRvIGNoZSB1bmEgY2F0ZWdvcmlhIGNlIGwnaGEsIHF1aSBzaSBMRUdHRSBxdWFsZSDigJQgY29zaScgY2hpCiAgICAgICAgICAgIGFwcmUgaWwgY2FtcG8gdmVkZSBjaGUgw6ggZ2nDoCBwaWVubyBkaSBzdW8gZSBjaGl1ZGUgc2VuemEgc2NyaXZlcmUuCiAgICAgICAgICAgIFNwYXJpc2NlIGFwcGVuYSBzaSBzY3JpdmUgcXVhbGNvc2E6IGRhIHF1ZWwgbW9tZW50byB2aW5jZSBsbwogICAgICAgICAgICBzY3JpdHRvLCBlIGRpcmUgZHVlIGNvc2UgZGl2ZXJzZSBpbnNpZW1lIGNvbmZvbmRlcmViYmUuICovfQogICAgICAgIHsoKCkgPT4gewogICAgICAgICAgY29uc3QgZGFsID0gY2F0ZWdvcmlhQWdnKHN0YXRvLCB7IGRpc3RpbnRhOiBkaXN0aW50YS5maWx0ZXIoKGQpID0+IGQucHJvZG90dG9JZCkgfSk7CiAgICAgICAgICBpZiAoIWRhbCB8fCBjYXRlZ29yaWEudHJpbSgpKSByZXR1cm4gbnVsbDsKICAgICAgICAgIHJldHVybiAoCiAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0idGV4dC14cyBtdC0xLjUiIHN0eWxlPXt7IGNvbG9yOiBULmJsdSB9fT4KICAgICAgICAgICAgICBEYWwgbWFnYXp6aW5vOiA8Yj57ZGFsfTwvYj4g4oCUIG5vbiBzZXJ2ZSByaXNjcml2ZXJsYS4KICAgICAgICAgICAgPC9wPgogICAgICAgICAgKTsKICAgICAgICB9KSgpfQo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p039', substr((select value from kv_store where key='app:jsx:src'), 773950, 36238)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p040', convert_from(decode('ICAvKiDilIDilIAgTCdPUkRJTkUgREVHTEkgSU5HUkVESUVOVEkgRScgTCdBTEZBQkVUTyAoZ2VuLTYuMTcpIOKUgOKUgAogICAgIFF1aSBzdGF2YW5vIMKrYmF0dHV0ZUFnZ8K7IGUgwqtwZXJCYW5jb8K7OiBvcmRpbmF2YW5vIGkgY2hpcCBwZXIgcXVhbnRlIHZvbHRlCiAgICAgZXJhbm8gc3RhdGkgYmF0dHV0aSwgZSBsYSByYWdpb25lIHNjcml0dGEgZXJhIGNoZSBsYSBmYXNjaWEgZXJhIHVuYSByaWdhCiAgICAgc29sYSBlIHN1IDM5MHB4IHNlIG5lIHZlZGV2YW5vIGR1ZSBlIG1lenpvIOKAlCBxdWluZGkgbGUgZHVlIHBpdScgcHJvYmFiaWxpCiAgICAgYW5kYXZhbm8gbWVzc2Ugc290dG8gaWwgcG9sbGljZS4KICAgICBRdWVsbGEgcmFnaW9uZSBub24gYydlJyBwaXUnIHBlciBkdWUgbW90aXZpLCBlIHR1dHRpIGUgZHVlIGNvbnRhbm8uIElsCiAgICAgcHJpbW86IGRhIG9nZ2kgaSBjaGlwIFZBTk5PIEEgQ0FQTywgc2UgbmUgdmVkb25vIHF1YXR0cm8sIGUgbm9uIGMnZScgcGl1JwogICAgIHVuYSBmZXJpdG9pYSBkYSBvdHRpbWl6emFyZS4gSWwgc2Vjb25kbywgY2hlIGJhc3RlcmViYmUgZGEgc29sbyDigJQgVmFsZXJpbwogICAgIGlsIDEzIHNldHRlbWJyZTogwqtjb24gemVybyBjYXRlZ29yaWUgdmEgaW4gb3JkaW5lIGFsZmFiZXRpY2/Cuy4gSWwgZGl0byBub24KICAgICBjZXJjYSDCq2xhIHBpdScgcHJvYmFiaWxlwrssIGNlcmNhIFVOQSBQQVJPTEEgY2hlIHNhIGdpYScsIGUgdW5hIHBhcm9sYSBzaQogICAgIHRyb3ZhIGluIGFsZmFiZXRvLiBMJ29yZGluZSBwZXIgYmF0dHV0ZSByZXN0YSBkb3ZlIHNlcnZlIGFuY29yYTogc3VpCiAgICAgR1JVUFBJIGRlbCBsaXN0aW5vLCBkb3ZlIG5vbiBjJ2UnIG5lc3N1bmEgcGFyb2xhIGRhIGNlcmNhcmUuCiAgICAgTmllbnRlIGRhIHJpb3JkaW5hcmU6IGFnZ2l1bnRlRGkgZSBhZ2dpdW50ZVR1dHRlIG9yZGluYW5vIGdpYScgaW4KICAgICBhbGZhYmV0bywgZSBsZSBkdWUgZnVuemlvbmkgc2UgbmUgdmFubm8gaW52ZWNlIGRpIHJlc3RhcmUgcXVpIHNwZW50ZS4gKi8K', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p041', substr((select value from kv_store where key='app:jsx:src'), 810751, 1100)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p042', convert_from(decode('ICAgICAgLyogbm9uIHBpdScgwqthLmNhdGVnb3JpYcK7IHNvbHRhbnRvOiBzZSBub24gZScgc2NyaXR0YSBzaSBsZWdnZSBkYWwKICAgICAgICAgcHJvZG90dG8gZGVsbGEgZGlzdGludGEgKGdlbi02LjE3LCBjYXRlZ29yaWFBZ2cpICovCiAgICAgIGNvbnN0IGMgPSBjYXRlZ29yaWFBZ2coc3RhdG8sIGEpIHx8IFNFTlpBX0NBVDsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p043', substr((select value from kv_store where key='app:jsx:src'), 811908, 627)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p044', convert_from(decode('ICAgIG5ldyBTZXQobC5tYXAoKGEpID0+IGNhdGVnb3JpYUFnZyhzdGF0bywgYSkgfHwgU0VOWkFfQ0FUKSkuc2l6ZSA+IDE7Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p045', substr((select value from kv_store where key='app:jsx:src'), 812612, 39001)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p046', convert_from(decode('ICAgICAgICBjb25zdCBjaGlwcyA9IHJ2ID8gYWdnaXVudGVEZWxHcnVwcG8ocnYuZ3J1cHBvKSA6IGFnZ2l1bnRlVHV0dGUoc3RhdG8pOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p047', substr((select value from kv_store where key='app:jsx:src'), 851703, 5021)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p048', convert_from(decode('ICAgICAgICAgICAgICAgIC8qIFNFTlpBIGNhdGVnb3JpZSB2ZXJlLCBVTkEgR1JJR0xJQSBDSEUgVkEgQSBDQVBPIChnZW4tNi4xNywKICAgICAgICAgICAgICAgICAgIHBhcm9sZSBkaSBWYWxlcmlvOiDCq2xlIGFnZ2l1bnRlIGhhbm5vIHVuYSBiYXJyYSBwb2NvIHV0aWxlwrspLgogICAgICAgICAgICAgICAgICAgRXJhIHVuYSBmaWxhIGNoZSBzY29ycmV2YSBkaSBsYXRvOiBzdSAzOTBweCBzaSB2ZWRldmFubyBkdWUKICAgICAgICAgICAgICAgICAgIGNoaXAgZSBtZXp6byBzdSB2ZW50aXRyZScsIGUgaWwgcmVzdG8gc3RhdmEgb2x0cmUgaWwgYm9yZG8KICAgICAgICAgICAgICAgICAgIHNlbnphIGNoZSBuaWVudGUgbG8gZmFjZXNzZSBjYXBpcmUg4oCUIGxhIHN0ZXNzYSBmb3JtYSBjaGUgYQogICAgICAgICAgICAgICAgICAgZ2VuLTUuNTIgYXZldmEgZ2lhJyByb3R0byBsYSBiYXJyYSBkaSBuYXZpZ2F6aW9uZS4KICAgICAgICAgICAgICAgICAgIEFkZXNzbyBzZSBuZSB2ZWRvbm8gcXVhdHRybyBlIHNpIHNjb3JyZSBjb2wgcG9sbGljZSBpbiBnaXUnLAogICAgICAgICAgICAgICAgICAgY29tZSBpbiB0dXR0byBpbCByZXN0byBkZWxsJ2FwcC4gQ29zdGEgNTJweCBpbiBwaXUnIFNPTE8gYQogICAgICAgICAgICAgICAgICAgZmFzY2lhIGFwZXJ0YSAoMTY1IGNvbnRybyAxMTMpLCBzb3R0byBpIDIwOSBjaGUgZ2VuLTYuMDQgaGEKICAgICAgICAgICAgICAgICAgIGdpdWRpY2F0byB0cm9wcGk7IGNoaXVzYSBub24gY2FtYmlhIGRpIHVuIHBpeGVsLgogICAgICAgICAgICAgICAgICAgSWwgdGV0dG8gYSA2LjFyZW0gc29ubyBkdWUgcmlnaGUgZGkgY2hpcDogb2x0cmUsIHNpIHNjb3JyZS4gKi8K', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p049', substr((select value from kv_store where key='app:jsx:src'), 856878, 44)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p050', convert_from(decode('ICAgICAgICAgICAgICAgICAgcmV0dXJuIDxkaXYgY2xhc3NOYW1lPSJmbGV4IGZsZXgtd3JhcCBnYXAtMiBvdmVyZmxvdy15LWF1dG8gc2Mtc2Nyb2xsIgogICAgICAgICAgICAgICAgICAgIHN0eWxlPXt7IG1heEhlaWdodDogIjYuMXJlbSIgfX0+e2NoaXBzLm1hcCh1bkNoaXApfTwvZGl2PjsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p051', substr((select value from kv_store where key='app:jsx:src'), 857018, 789)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p052', convert_from(decode('ICAgICAgICAgICAgICAgICAgICAgIDxkaXYga2V5PXtjYXR9IGRhdGEtY2F0PXtjYXR9IGNsYXNzTmFtZT0iZmxleCBpdGVtcy1zdGFydCBnYXAtMiI+CiAgICAgICAgICAgICAgICAgICAgICAgIHsvKiBsJ2V0aWNoZXR0YSBzdGEgaW4gQUxUTyBlIG5vbiBhbCBjZW50cm86IGNvbiBpIGNoaXAKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHN1IGR1ZSByaWdoZSwgY2VudHJhdGEgZ2FsbGVnZ2VyZWJiZSBpbiBtZXp6byBhbGxhCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBjYXRlZ29yaWEgaW52ZWNlIGRpIGludGl0b2xhcmxhIChnZW4tNi4xNykgKi99Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p053', substr((select value from kv_store where key='app:jsx:src'), 857896, 113)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p054', convert_from(decode('ICAgICAgICAgICAgICAgICAgICAgICAgICBzdHlsZT17eyBjb2xvcjogVC50ZW51ZSwgd2lkdGg6ICI0LjZyZW0iLCBwYWRkaW5nVG9wOiAiMC45cmVtIiB9fT57Y2F0fTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImZsZXggZmxleC13cmFwIGdhcC0yIj57YWdncy5tYXAodW5DaGlwKX08L2Rpdj4K', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen617:p055', substr((select value from kv_store where key='app:jsx:src'), 858185, 130128)) on conflict (key) do update set value=excluded.value;

-- il cancello, PRIMA di scrivere
select md5(string_agg(value, '' order by key)) as md5_ricomposto,
       length(string_agg(value, '' order by key)) as len_ricomposto,
       md5(string_agg(value, '' order by key)) = 'f96ad21282fa8f09b48696aa3f0ba5a9' as combacia
from kv_store where key like 'tmp:gen617:p%';

update kv_store set value = (select string_agg(value, '' order by key) from kv_store where key like 'tmp:gen617:p%')
where key='app:jsx:src'
  and md5(value) = 'cf97cfd7ced5c37f3d7d468d9486d5bb'
  and (select md5(string_agg(value, '' order by key)) from kv_store where key like 'tmp:gen617:p%') = 'f96ad21282fa8f09b48696aa3f0ba5a9';

update kv_store set value = '{"len":997686,"ver":"gen-6.17"}'
where key='app:jsx:meta'
  and (select md5(value) from kv_store where key='app:jsx:src') = 'f96ad21282fa8f09b48696aa3f0ba5a9';

delete from kv_store where key like 'tmp:gen617:p%';
