-- gen621: 13 zone cambiate, 27 tessere
-- 33979df5b436f10204137719e14a7d06 (1042138) → c230922976fc1191d6f38b868edb753f (1047212)

insert into kv_store(key, value) select 'backup:pre-gen621', value from kv_store where key='app:jsx:src'
  on conflict (key) do update set value=excluded.value;

insert into kv_store(key, value) values('tmp:gen621:p001', substr((select value from kv_store where key='app:jsx:src'), 1, 9434)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p002', convert_from(decode('LyogbCd1bHRpbW8gbnVtZXJvIGNoZSBITyBzY3JpdHRvIHN1bGxhIHNwaWE6IHNlcnZlIGEgbm9uIGZhcmxhIHNjZW5kZXJlCiAgIChnZW4tNi4yMSwgdmVkaSBzY3JpdmlSZW1vdG8pICovCmxldCBzcGlhU2NyaXR0YSA9IDA7Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p003', substr((select value from kv_store where key='app:jsx:src'), 9435, 3879)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p004', convert_from(decode('ICAgIC8qIOKUgOKUgCBMQSBTUElBIE5PTiBUT1JOQSBJTkRJRVRSTyAoZ2VuLTYuMjEpIOKUgOKUgAogICAgICAgUXVlc3RhIHJpZ2Egc3RhIERPUE8gbG8gc3RhdG8gZSBzdSB1bmEgY2hpYXZlIGNoZSBpbCBjYW5jZWxsbyBkZWwgc2VydmVyCiAgICAgICBub24gcHJvdGVnZ2UgKGFwcF9rdl9zZXQuc3FsIGd1YXJkYSBzb2xvIHNjcDpzdGF0bzp2MSkuIFVuIGNpY2xvIGRpCiAgICAgICBzYWx2YXRhZ2dpbyByaW1hc3RvIGFwcGVzbyBvbHRyZSBpIGRvZGljaSBzZWNvbmRpIGRlbCB3YXRjaGRvZyByaWVudHJhCiAgICAgICBxdWFuZG8gdW4gYWx0cm8gaGEgZ2lhJyBzY3JpdHRvLCBlIHF1aSByaXNjcml2ZXZhIGlsIFBST1BSSU8gbnVtZXJvLCBwaXUnCiAgICAgICBiYXNzbzogZGEgcXVlbCBtb21lbnRvIGlsIHBvbGwgZGkgb2duaSB0ZWxlZm9ubyBmZXJtbyBhIHF1ZWxsYSByZXZpc2lvbmUKICAgICAgIGNhZGUgbmVsIGdpcm8gbWFncm8gZSBub24gY2hpZWRlIHBpdScgbGEgbGlzdGEgcGVyIGRpZWNpIGdpcmksIGNpb2UnCiAgICAgICAyNi0zNSBzZWNvbmRpIOKAlCBlZCBlJyBjaWVjbyBlc2F0dGFtZW50ZSBzdWkgdGVsZWZvbmkgYSBjdWkgbWFuY2EKICAgICAgIGwndWx0aW1hIHZlbmRpdGEuIFNpIHNjcml2ZSBzb2xvIHNlIGlsIG51bWVybyBTQUxFLCBlIHNpIHRpbWJyYSBzb2xvCiAgICAgICBkb3BvIGNoZSBsYSBzY3JpdHR1cmEgZScgYW5kYXRhIGEgYnVvbiBmaW5lLgogICAgICAgTElNSVRFIERJQ0hJQVJBVE86IHF1ZXN0YSBtZW1vcmlhIGUnIE1JQSwgcXVpbmRpIGZlcm1hIHNvbG8gbGUgbWllCiAgICAgICBzY3JpdHR1cmUgYWxsJ2luZGlldHJvLiBMYSBzcGlhIGUnIGdsb2JhbGUgZSB1biBhbHRybyBkaXNwb3NpdGl2byBwdW8nCiAgICAgICBzZW1wcmUgcmlzY3JpdmVybGEgcGl1JyBiYXNzYTogbGEgY3VyYSBjb21wbGV0YSBlJyB1biBjYW5jZWxsbyBzdSBxdWVsbGEKICAgICAgIGNoaWF2ZSBkZW50cm8gaWwgc2VydmVyLCBjaW9lJyBpbCBwYXZpbWVudG8gZGVsIHRyYWZmaWNvLiAqLwogICAgaWYgKChzdGF0by5yZXYgfHwgMCkgPiBzcGlhU2NyaXR0YSkgewogICAgICB0cnkgewogICAgICAgIGF3YWl0IHdpbmRvdy5zdG9yYWdlLnNldChDSElBVkVfUkVWLCBTdHJpbmcoc3RhdG8ucmV2IHx8IDApLCB0cnVlKTsKICAgICAgICBzcGlhU2NyaXR0YSA9IHN0YXRvLnJldiB8fCAwOwogICAgICB9IGNhdGNoIHt9CiAgICB9Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p005', substr((select value from kv_store where key='app:jsx:src'), 13403, 27378)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p006', convert_from(decode('Y29uc3QgVkVSU0lPTkUgPSAiZ2VuLTYuMjEiOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p007', substr((select value from kv_store where key='app:jsx:src'), 40810, 950139)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p008', convert_from(decode('ICAvKiDilIDilIAgSUwgTlVNRVJPIERJIEdJUk8gKGdlbi02LjIxKSDilIDilIAKICAgICBJbCB3YXRjaGRvZyBxdWkgc290dG8gbGFzY2lhIHBhcnRpcmUgdW4gU0VDT05ETyBjaWNsbyBkaSBzYWx2YXRhZ2dpbwogICAgIHF1YW5kbyBpbCBwcmltbyBlJyBhcHBlc28gZGEgcGl1JyBkaSBkb2RpY2kgc2Vjb25kaTogZScgZ2l1c3RvLCBzZSBubyB1bgogICAgIHRlbGVmb25vIGNvbiBsYSByZXRlIGltcGFudGFuYXRhIG5vbiBzYWx2ZXJlYmJlIHBpdScgbmllbnRlLiBNYSBxdWFuZG8gaWwKICAgICBjaWNsbyBsZW50byByaWVudHJhIHNpIGNvbXBvcnRhdmEgY29tZSBzZSBmb3NzZSBsJ3VsdGltbyDigJQgcmltZXR0ZXZhIGxhCiAgICAgcHJvcHJpYSBiYXNlIHZlY2NoaWEsIGNpIHJpY29zdHJ1aXZhIHNvcHJhIGxhIHZpc3RhLCBhenplcmF2YSBpbCBzZW1hZm9ybwogICAgIGUgcmlhcHJpdmEgaWwgcnViaW5ldHRvLiBRdWVzdG8gY29udGF0b3JlIHNlcnZlIGEgdW5hIGRvbWFuZGEgc29sYSwgZSBsYQogICAgIHJpc3Bvc3RhIHNpIHNhIHNlbnphIGd1YXJkYXJlIGkgZGF0aTogwqtzb25vIGFuY29yYSBpbyBsJ3VsdGltbz/Cuy4gKi8KICBjb25zdCBnaXJvUmVmID0gdXNlUmVmKDApOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p009', substr((select value from kv_store where key='app:jsx:src'), 990949, 10716)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p010', convert_from(decode('ICAgIGNvbnN0IG1pbyA9ICsrZ2lyb1JlZi5jdXJyZW50Owo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p011', substr((select value from kv_store where key='app:jsx:src'), 1001665, 3968)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p012', convert_from(decode('ICAgICAgLyog4pSA4pSAIExFIFZPQ0kgQ0hFIFBBUlRPTk8gU0kgQ09OVEFOTyBQRVIgTk9NRSAoZ2VuLTYuMjEpIOKUgOKUgAogICAgICAgICDCq2ludmlhdGXCuyBlJyB1bmEgTFVOR0hFWlpBLCBlIGFsIHJpdG9ybm8gc2Vydml2YSBhIHRhZ2xpYXJlIGxhIGNvZGEKICAgICAgICAgcGVyIFBPU0laSU9ORS4gRnJhIGxhIHBhcnRlbnphIGUgaWwgcml0b3JubyBjJ2UnIHVuIGF3YWl0LCBlIGNvbiBkdWUKICAgICAgICAgY2ljbGkgY2hlIGNvbnZpdm9ubyBsYSBjb2RhIGluIG1lenpvIGNhbWJpYTogaWwgY2ljbG8gbGVudG8gdGFnbGlhdmEKICAgICAgICAgdW4gbnVtZXJvIGRpIHBvc2l6aW9uaSBjYWxjb2xhdG8gc3UgdW5hIGNvZGEgZ2lhJyBhY2NvcmNpYXRhCiAgICAgICAgIGRhbGwnYWx0cm8sIGUgbGUgdm9jaSBjaGUgY2FkZXZhbm8gZXJhbm8gbGUgUElVJyBOVU9WRSDigJQgZ2xpIHNjb250cmluaQogICAgICAgICBiYXR0dXRpIG5lbCBmcmF0dGVtcG8uIE1pc3VyYXRvIGluIGNvbGxhdWRpL3NvcnBhc3NhdG90ZXN0Lm1qcyDCpzE6IGxhCiAgICAgICAgIGdpb3JuYXRhIHNpIGZlcm1hIGEgZHVlIHZlbmRpdGUgc3UgdHJlLCBzZW56YSB1bmEgcmlnYSBlIGNvbCBwYWxsaW5vCiAgICAgICAgIHZlcmRlLgogICAgICAgICBMYSBmb3RvZ3JhZmlhIHNpIHByZW5kZSBRVUksIGRvdmUgbmFzY2UgwqtpbnZpYXRlwrssIGUgbm9uIHBpdScgaW4KICAgICAgICAgYmFzc28gYWNjYW50byBhbCB0aW1icm86IGlsIHJhbW8gZGVsbGEgc2NvcmNpYXRvaWEgKHBvY2hlIHJpZ2hlIHNvdHRvKQogICAgICAgICBsYSB1c2VyZWJiZSBwcmltYSBjaGUgc2lhIGRpY2hpYXJhdGEsIGUgc2FyZWJiZSB1biBSZWZlcmVuY2VFcnJvciBpbgogICAgICAgICB1bmEgc3RyYWRhIGNoZSBzaSBwZXJjb3JyZSB0dXR0aSBpIGdpb3JuaS4gKi8KICAgICAgY29uc3QgcGFydGl0ZSA9IGNvZGFSZWYuY3VycmVudC5zbGljZSgwLCBpbnZpYXRlKTsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p013', substr((select value from kv_store where key='app:jsx:src'), 1005633, 625)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p014', convert_from(decode('ICAgICAgICAvKiBzdGVzc2EgZm9ybWEgZGVsIHRhZ2xpbyBkaSBzb3R0bywgZSBxdWkgZScgdW5hIHNjZWx0YSBkaQogICAgICAgICAgIGxlZ2dpYmlsaXRhJyBlIG5vbiB1bmEgcmlwYXJhemlvbmU6IGZyYSDCq2ludmlhdGXCuyBlIHF1ZXN0YSByaWdhIG5vbgogICAgICAgICAgIGMnZScgbmVzc3VuIGF3YWl0LCBxdWluZGkgwqtwYXJ0aXRlwrsgZScgdHV0dGEgbGEgY29kYSBlIGxlIGR1ZSBmb3JtZQogICAgICAgICAgIHNvbm8gaWRlbnRpY2hlLiBTaSBzY3JpdmUgdWd1YWxlIHBlcmNoZScgbGEgcmVnb2xhIHNpYSBVTkEsIGUgY2hpCiAgICAgICAgICAgbGVnZ2Ugbm9uIGRlYmJhIHJpY29yZGFyc2kgcXVhbGUgZGVpIGR1ZSByYW1pIGUnIHF1ZWxsbyBhbCBzaWN1cm8uICovCiAgICAgICAgY29kYVJlZi5jdXJyZW50ID0gY29kYVJlZi5jdXJyZW50LmZpbHRlcigobSkgPT4gIXBhcnRpdGUuaW5jbHVkZXMobSkpOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p015', substr((select value from kv_store where key='app:jsx:src'), 1006316, 24)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p016', convert_from(decode('ICAgICAgICAvKiBlIHVuIGNpY2xvIHNvcnBhc3NhdG8gc2kgZmVybWEgcXVpOiBoYSB0b2x0byBsZSBzdWUgdm9jaSwgZSB0dXR0bwogICAgICAgICAgIHF1ZWxsbyBjaGUgdmllbmUgZG9wbyBlJyByb2JhIGRhIHVsdGltbyBhcnJpdmF0byAodmVkaSBnaXJvUmVmKSAqLwogICAgICAgIGlmIChtaW8gIT09IGdpcm9SZWYuY3VycmVudCkgcmV0dXJuOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p017', substr((select value from kv_store where key='app:jsx:src'), 1006340, 4860)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p018', convert_from(decode('ICAgICAgY29kYVJlZi5jdXJyZW50ID0gY29kYVJlZi5jdXJyZW50LmZpbHRlcigobSkgPT4gIXBhcnRpdGUuaW5jbHVkZXMobSkpOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p019', substr((select value from kv_store where key='app:jsx:src'), 1011288, 95)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p020', convert_from(decode('ICAgICAgLyog4pSA4pSAIFVOIENJQ0xPIFNPUlBBU1NBVE8gTk9OIENPTUFOREEgUElVJyAoZ2VuLTYuMjEpIOKUgOKUgAogICAgICAgICBIYSBmYXR0byBpbCBzdW8gbWVzdGllcmU6IGxhIHN1YSBzY3JpdHR1cmEgZScgYXR0ZXJyYXRhIGUgbGUgc3VlIHZvY2kKICAgICAgICAgc29ubyB1c2NpdGUgZGFsbGEgY29kYS4gVHV0dG8gcXVlbGxvIGNoZSB2aWVuZSBkb3BvIHBhcmxhIGRpIEFERVNTTyDigJQKICAgICAgICAgcXVhbCBlJyBsYSBiYXNlLCBjb3NhIHNpIHZlZGUgYSBzY2hlcm1vLCBjaGUgY29sb3JlIGhhIGlsIHBhbGxpbm8sCiAgICAgICAgIHF1YW5kbyBwYXJ0ZSBpbCBwcm9zc2ltbyBnaXJvIOKAlCBlIGRpIGFkZXNzbyBzYSBxdWFsY29zYSBzb2xvIGwndWx0aW1vCiAgICAgICAgIGNpY2xvLiBQcmltYSBkaSBxdWVzdGEgcmlnYSBpbCBjaWNsbyBsZW50byByaW1ldHRldmEgdW5hIGJhc2UgcGl1JwogICAgICAgICB2ZWNjaGlhLCBjaSByaWNvc3RydWl2YSBzb3ByYSBsYSB2aXN0YSwgc2NyaXZldmEgwqtva8K7IGUgY29uIHBpYW5pZmljYQogICAgICAgICBmYWNldmEgcGFydGlyZSB1biBURVJaTyBjaWNsbyBtZW50cmUgaWwgc2Vjb25kbyBlcmEgYW5jb3JhIGluIHZvbG8KICAgICAgICAgKG1pc3VyYXRvIGluIHNvcnBhc3NhdG90ZXN0IMKnMjogdHJlIGluZ3Jlc3NpIG5lbGxhIHNjcml0dHVyYSBkb3ZlIG5lCiAgICAgICAgIGJhc3Rhbm8gZHVlKS4KICAgICAgICAgRSBOT04gc2kgYXp6ZXJhIGluU3luY1JlZjogaWwgZ3VpbnphZ2xpbyBkZWwgd2F0Y2hkb2cgZScgZGVsbCd1bHRpbW8KICAgICAgICAgY2ljbG8sIG5vbiBkaSBxdWVzdG8uICovCiAgICAgIGlmIChtaW8gIT09IGdpcm9SZWYuY3VycmVudCkgcmV0dXJuOwogICAgICBjb25mbGl0dGlSZWYuY3VycmVudCA9IDA7Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p021', substr((select value from kv_store where key='app:jsx:src'), 1011383, 540)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p022', convert_from(decode('ICAgICAgLyogdW4gY2ljbG8gc29ycGFzc2F0byBub24gcGFybGEgbmVtbWVubyBxdWFuZG8gZmFsbGlzY2U6IGlsIHNlbWFmb3JvLCBpbAogICAgICAgICBjb250byBkZWxsZSByaXByb3ZlIGUgaWwgcHJvc3NpbW8gYXBwdW50YW1lbnRvIHNvbm8gZGVsbCd1bHRpbW8gY2ljbG8sCiAgICAgICAgIGNoZSBlJyBhbmNvcmEgaW4gdm9sbyBlIHNhIHBpdScgY29zZSBkaSBsdWkgKGdlbi02LjIxKS4gTGEgY29kYSBxdWkKICAgICAgICAgbm9uIHNpIHRvY2NhIGluIG5lc3N1bm8gZGVpIGR1ZSBjYXNpLCBxdWluZGkgbm9uIGMnZScgbmllbnRlIGRhCiAgICAgICAgIHJpbWV0dGVyZSBhIHBvc3RvLiAqLwogICAgICBpZiAobWlvICE9PSBnaXJvUmVmLmN1cnJlbnQpIHJldHVybjsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p023', substr((select value from kv_store where key='app:jsx:src'), 1011923, 25075)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p024', convert_from(decode('ICAgIGNvbnN0IGluRmlsYSA9IGNvZGFSZWYuY3VycmVudC5sZW5ndGg7Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p025', substr((select value from kv_store where key='app:jsx:src'), 1037063, 22)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p026', convert_from(decode('ICAgICAgLyogU0kgQ09OVEEgVFVUVEEgTEEgQ09EQSwgZSBub24gcGl1JyBzb2xvIGxlIHZvY2kgY29uIHVuIHRpcG8KICAgICAgICAgKGdlbi02LjIxKS4gRHVlIHJpZ2hlIHNvdHRvIGMnZScgwqtjb2RhUmVmLmN1cnJlbnQgPSBbbV3CuywKICAgICAgICAgVU4nQVNTRUdOQVpJT05FIGNoZSBidXR0YSBUVVRUTzogYW5jaGUgbGUgbXV0YXppb25pIGEgY2xvc3VyZSDigJQgdW5hCiAgICAgICAgIGV2YXNpb25lLCB1bmEgcHJvZHV6aW9uZSwgdW4gY29udGVnZ2lvLCBsYSByaWdhIHN0ZXNzYSBkZWxsZSBmZXJtZSDigJQKICAgICAgICAgY2hlIG5vbiBoYW5ubyB0aXBvIGUgbm9uIHN0YW5ubyBzdWwgZGlzY28sIHF1aW5kaSBzcGFyaXJlYmJlcm8gc2VuemEKICAgICAgICAgbGFzY2lhcmUgbmllbnRlIGRhIG5lc3N1bmEgcGFydGUuIExhIGd1YXJkaWEgZXJhIHBpdScgc3RyZXR0YSBkZWwKICAgICAgICAgZGFubm8gY2hlIHByZXZpZW5lLCBlZCBlJyB1biBkaWZldHRvIHZlY2NoaW8gcXVhbnRvIGdlbi02LjEwOiBxdWVsbGEKICAgICAgICAgZ2VuZXJhemlvbmUgYXZldmEgY2hpdXNvIGlsIGJ1Y28gcGVyIGxlIHZlbmRpdGUgZSBsZSBzcHVudGUsIG5vbiBwZXIKICAgICAgICAgaWwgcmVzdG8uIElsIHNvc3RhbnRpdm8gZGljZSBnaWEnIMKrbW9kaWZpY2hlwrssIHF1aW5kaSBjaGkgcmlwcmlzdGluYQogICAgICAgICBsZWdnZSBsYSBzdGVzc2EgZnJhc2UgZGkgcHJpbWEuICovCg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen621:p027', substr((select value from kv_store where key='app:jsx:src'), 1037446, 4693)) on conflict (key) do update set value=excluded.value;

-- il cancello, PRIMA di scrivere
select md5(string_agg(value, '' order by key)) as md5_ricomposto,
       length(string_agg(value, '' order by key)) as len_ricomposto,
       md5(string_agg(value, '' order by key)) = 'c230922976fc1191d6f38b868edb753f' as combacia
from kv_store where key like 'tmp:gen621:p%';

update kv_store set value = (select string_agg(value, '' order by key) from kv_store where key like 'tmp:gen621:p%')
where key='app:jsx:src'
  and md5(value) = '33979df5b436f10204137719e14a7d06'
  and (select md5(string_agg(value, '' order by key)) from kv_store where key like 'tmp:gen621:p%') = 'c230922976fc1191d6f38b868edb753f';

update kv_store set value = '{"len":1047212,"ver":"gen-6.21"}'
where key='app:jsx:meta'
  and (select md5(value) from kv_store where key='app:jsx:src') = 'c230922976fc1191d6f38b868edb753f';

delete from kv_store where key like 'tmp:gen621:p%';
