-- gen624: 18 zone cambiate, 37 tessere
-- 3867679ff319995d9024e18abc4b2425 (1063404) → cd1d92142ea7e891be2e35266859cb50 (1069982)

insert into kv_store(key, value) select 'backup:pre-gen624', value from kv_store where key='app:jsx:src'
  on conflict (key) do update set value=excluded.value;

insert into kv_store(key, value) values('tmp:gen624:p001', substr((select value from kv_store where key='app:jsx:src'), 1, 42033)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p002', convert_from(decode('Y29uc3QgVkVSU0lPTkUgPSAiZ2VuLTYuMjQiOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p003', substr((select value from kv_store where key='app:jsx:src'), 42063, 133833)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p004', convert_from(decode('ICAg4pSA4pSAIElMIE1FU1RJRVJFIFVOSUNPIEUnIERFTCBQUk9GSUxPLCBOT04gREVMTEEgU1VBIExJU1RBIChnZW4tNi4yNCkg4pSA4pSACiAgIEZpbm8gYSBnZW4tNi4yMyBxdWVzdGkgZHVlIGNoaWVkZXZhbm8gYW5jaGUgwqtlIGFsbWVubyB1bmEgcG9zdGF6aW9uZSAvIHVuCiAgIG1hZ2F6emlubyBhc3NlZ25hdG/Cuy4gU2VtYnJhdmEgcHJ1ZGVuemEg4oCUIMKrYXBwZXNvIGEgY2lvJyBjaGUgcmVuZGUgaWwKICAgbWVzdGllcmUgcG9zc2liaWxlwrsg4oCUIGVkIGVyYSBpbnZlY2UgdW5hIGNvbnRyYWRkaXppb25lLCB0cm92YXRhIGRlbW9sZW5kbwogICBpbCBkaXNlZ25vIGRpIGdlbi02LjI0IGUgTUlTVVJBVEEgYWZmaWFuY2FuZG8gaSBkdWUgc3RhdGk6CiAgIMK3IGNhbmNlbGxhdGEgbCd1bHRpbWEgcG9zdGF6aW9uZSwgbCdpZCByZXN0YXZhIGFwcGVzbywgbGEgbHVuZ2hlenphIGVyYSAxLAogICAgIGlsIHByZWRpY2F0byByZXN0YXZhIHZlcm8gZSBpbCByYWdhenpvIHNpIHRyb3ZhdmEgY2hpdXNvIGluIHVuYSBzdGFuemEKICAgICB2dW90YSBzZW56YSBzYXBlcmxvOwogICDCtyBlIGxhIGN1cmEgb3Z2aWEg4oCUIHJpcHVsaXJlIGxhIGxpc3RhIGNvbiB1bmEgY2FzY2F0YSDigJQgcG9ydGF2YSBsYQogICAgIGx1bmdoZXp6YSBhIDAsIGlsIHByZWRpY2F0byBhIGZhbHNvLCBlIGxhIEJBUlJBIFBJRU5BOiBjaW9lJyByZWdhbGF2YSBhCiAgICAgcXVlbCBwcm9maWxvIHNlemlvbmkgY2hlIG5lc3N1bm8gYXZldmEgYWNjZXNvLiBMYSBkZWR1emlvbmUgYWwgY29udHJhcmlvLAogICAgIGxvIHN0ZXNzbyBwZWNjYXRvIHZpZXRhdG8gcXVpIHNvcHJhLgogICBJIGR1ZSBndWFzdGkgZXJhbm8gTE8gU1RFU1NPIEVWRU5UTyBjb24gZHVlIHZlcmRldHRpIG9wcG9zdGkuIExhIGRvbWFuZGEKICAgY2hlIG1hbmNhdmEgZXJhIHVuYSBzb2xhOiBjb3NhIGRldmUgdmVkZXJlIHVuIG1lc3RpZXJlIHVuaWNvIHF1YW5kbyBsYSBzdWEKICAgc3RhbnphIGUnIHZ1b3RhPyBSaXNwb3N0YSBzY2VsdGEgZSBzY3JpdHRhOiBSRVNUQSBORUwgU1VPIE1FU1RJRVJFLCBlIGxhCiAgIHN0YW56YSBkaWNlIGxhIHZlcml0YScuIE5vbiBjb3N0YSB1bmEgc2NoZXJtYXRhIG51b3ZhLCBwZXJjaGUnIGxlIGR1ZQogICBzdGFuemUgdnVvdGUgbGEgZGljb25vIGdpYScg4oCUIMKrTm9uIGNpIHNvbm8gYW5jb3JhIHBvc3RhemlvbmkgwrcgTGUgZGlzZWduYQogICB1biBBZG1pbiBkYSBHZXN0aW9uZSDihpIgTGlzdGlub8K7IGUgwqtOZXNzdW4gbWFnYXp6aW5vIGxpbmVhIGFzc2VnbmF0byDCtwogICBDaGllZGkgYSB1biBBZG1pbiBkaSBhc3NlZ25hcnRlbGnCuyDigJQgY29uIGwndXNjaXRhIGluIGFsdG8gYSBkZXN0cmEgZG92J2UnCiAgIHNlbXByZSBzdGF0YS4gbWVzdGllcmV1bmljb3Rlc3QgwqcyNyBlIMKnMjggc29ubyBpIGd1YXJkaWFuaSwgZSBzb25vIG5hdGkKICAgcm9zc2kgcHJvcHJpbyBzdSBxdWVzdG8uICovCg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p005', substr((select value from kv_store where key='app:jsx:src'), 176142, 35)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p006', convert_from(decode('ICByZXR1cm4gcHJvZmlsbz8ucnVvbG8gIT09ICJhZG1pbiIgJiYgISFwcm9maWxvPy5zb2xvUG9zdGF6aW9uaTsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p007', substr((select value from kv_store where key='app:jsx:src'), 176288, 35)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p008', convert_from(decode('ICByZXR1cm4gcHJvZmlsbz8ucnVvbG8gIT09ICJhZG1pbiIgJiYgISFwcm9maWxvPy5zb2xvQ29udGVnZ2k7Cn0KLyog4pSA4pSAIFVOQSBET01BTkRBIFNPTEEsIEUgRElDRSBBTkNIRSBRVUFMRSBTVEFOWkEgKGdlbi02LjI0KSDilIDilIAKICAgZ2VuLTYuMjMgaGEgZmF0dG8gaSBkdWUgZ2VtZWxsaSBtYSBsaSBoYSBwb3J0YXRpIHNvbG8gc3UgYmFycmEsIGF0dGVycmFnZ2lvCiAgIGUgbXVybzogbGEgbGVudGUsIGlsIHRhc3RvIMKrP8K7IGUgaWwgZ2lybyBndWlkYXRvIGNvbnRpbnVhdmFubyBhIGNoaWVkZXJlCiAgIMKrc29sb0Nhc3NhP8K7IGUgYSByaXNwb25kZXJzaSBkaSBuby4gVHJlIGRvbWFuZGUgZGl2ZXJzZSBwZXIgbGEgc3Rlc3NhIGNvc2EKICAgc29ubyBpbCBtb2RvIGluIGN1aSB1biBtZXN0aWVyZSB1bmljbyByZXN0YSB1bmljbyBBIE1FVEEnLgogICBSZXN0aXR1aXNjZSBsJ0lEIERFTExBIFZJU1RBLCBub24gdW4nZXRpY2hldHRhIG51b3ZhOiBjaGkgZmlsdHJhIGRldmUKICAgc2FwZXJlIGNvc2EgbGFzY2lhciBwYXNzYXJlLCBub24gc29sbyBjb3NhIGJsb2NjYXJlLCBlIGNvc2knIG5vbiBuYXNjZSB1bmEKICAgc2Vjb25kYSB0YWJlbGxhIGRhIHRlbmVyZSBhbGxpbmVhdGEuICovCmZ1bmN0aW9uIG1lc3RpZXJlVW5pY28ocHJvZmlsbykgewogIGlmIChzb2xvQ2Fzc2EocHJvZmlsbykpIHJldHVybiAiY2Fzc2EiOwogIGlmIChzb2xvUG9zdGF6aW9uaShwcm9maWxvKSkgcmV0dXJuICJjb21hbmRlIjsKICBpZiAoc29sb0NvbnRlZ2dpKHByb2ZpbG8pKSByZXR1cm4gImNvbnRlZ2dpIjsKICByZXR1cm4gbnVsbDsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p009', substr((select value from kv_store where key='app:jsx:src'), 176431, 102928)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p010', convert_from(decode('ICAvKiDilIDilIAgTEEgRE9NQU5EQSBFJyBVTkEgU09MQSAoZ2VuLTYuMjQpIOKUgOKUgAogICAgIExlIHRyZSBjb3N0YW50aSByZXN0YW5vLCBlIHNlcnZvbm86IGxlIHRyZSBjbGF1c29sZSBkZWwgbXVybyBxdWkgc290dG8KICAgICBzb25vIHNjcml0dGUgcGVyIGVzdGVzbyBwZXJjaGUnIFRSRSBTRU5USU5FTExFIFNVTCBTT1JHRU5URSBsZSBsZWdnb25vCiAgICAgcGVyIG5vbWUgKGNhc3NhNjE3dGVzdCDCpzE0LCBtZXN0aWVyZXVuaWNvdGVzdCDCpzMgZSDCpzYpIHBpdScgbCdhbmNvcmEgZGVsCiAgICAgc2Fib3RhZ2dpbyBTNi4gSWwgZGlzZWdubyBjaGUgbGUgZm9uZGV2YSBpbiB1bmEgcmlnYSBzb2xhIGUnIHN0YXRvCiAgICAgZGVtb2xpdG86IGxhIGNvbnRyb3Byb3ZhIGwnaGEgY29zdHJ1aXRvIGUgZ2lyYXRvLCBlIGhhIG1vc3RyYXRvIGNoZSBjb24gaQogICAgIG5vbWkgcmltZXNzaSBpbiB1biBDT01NRU5UTyBxdWVsbGUgc2VudGluZWxsZSB0b3JuYW5vIHZlcmRpIGNvbCBtdXJvCiAgICAgdG9sdG8uIExhIHJpZ2EgdW5pY2Egbm9uIHZhbGV2YSBuaWVudGU7IGxhIGRvbWFuZGEgdW5pY2EsIHNpJy4gKi8KICBjb25zdCB1bmljbyA9IG1lc3RpZXJlVW5pY28ocHJvZmlsbyk7CiAgY29uc3Qgc29sb1F1aSA9IHVuaWNvID09PSAiY2Fzc2EiOwogIGNvbnN0IHNvbG9Qb3N0ID0gdW5pY28gPT09ICJjb21hbmRlIjsKICBjb25zdCBzb2xvQ29udCA9IHVuaWNvID09PSAiY29udGVnZ2kiOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p011', substr((select value from kv_store where key='app:jsx:src'), 279483, 11774)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p012', convert_from(decode('ICAgICAgLyogZ2VuLTYuMjQ6IHZhbGUgcGVyIFRVVFRJIGUgdHJlIGkgbWVzdGllcmkgdW5pY2ksIG5vbiBwZXIgbGEgc29sYQogICAgICAgICBjYXNzYS4gTGEgZnJhc2UgcXVpIHNvcHJhIOKAlCDCq2xhIHBhbm9yYW1pY2EgcmFjY29udGEgQ29udGEgwrcgT3JkaW5hIMK3CiAgICAgICAgIFJpY2V2aSwgY2hlIGUnIGlsIG1lc3RpZXJlIGRpIHVuIGFsdHJvwrsg4oCUIGFpIGR1ZSBnZW1lbGxpIHZhbGV2YQogICAgICAgICBwYXJvbGEgcGVyIHBhcm9sYSwgZSBpbCBjb2RpY2Ugbm9uIGxpIG5vbWluYXZhOiBhIHVuIHBpenphaW9sbwogICAgICAgICBwYXJ0aXZhbm8gYWRkb3NzbyBkYSBzb2xlIFNFVFRFIHNjaGVybWF0ZSBzdSB1biBtZXN0aWVyZSBjaGUgbm9uIGUnCiAgICAgICAgIGlsIHN1bywgY29uIGRlbnRybyBzZXppb25pIGNoZSBwb2kgdHJvdmEgbXVyYXRlLiBFcmEgbGEgcGVyZGl0YSBwaXUnCiAgICAgICAgIGdyYXZlIHBlcmNoZScgZXJhIE1VVEE6IG5lc3N1bm8gbGEgdG9jY2EsIGFycml2YSBhZGRvc3NvLiAqLwogICAgICBpZiAoIXVuaWNvICYmICFsb2NhbFN0b3JhZ2UuZ2V0SXRlbShrKSAmJiAhbG9jYWxTdG9yYWdlLmdldEl0ZW0oInNjcDp0b3VyOnYxIikpIHNldEd1aWRhKHBhc3NpUGFub3JhbWljYShOQVYpKTsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p013', substr((select value from kv_store where key='app:jsx:src'), 291377, 12623)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p014', convert_from(decode('ICAgICAgICAgIHsvKiBhIGNoaSBoYSBVTkEgc3RhbnphIHNvbGEgcXVlc3RlIGR1ZSBub24gc2kgb2Zmcm9ubzogbGEgUGxhbmNpYQo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p015', substr((select value from kv_store where key='app:jsx:src'), 304076, 216)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p016', convert_from(decode('ICAgICAgICAgICAgICBGVU9SSV9CQVJSQSAoZ2VuLTYuMTcpLgogICAgICAgICAgICAgIGdlbi02LjI0OiBsYSBndWFyZGlhIGVyYSBgIXNvbG9RdWlgIGUgbm9taW5hdmEgbGEgc29sYSBjYXNzYTsKICAgICAgICAgICAgICBhZGVzc28gZScgYCF1bmljb2AgZSB2YWxlIHBlciB0dXR0aSBlIHRyZS4gKi99CiAgICAgICAgICB7IXVuaWNvICYmICg8Pgo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p017', substr((select value from kv_store where key='app:jsx:src'), 304361, 54781)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p018', convert_from(decode('ICAgIC8qIGdlbi02LjI0OiBsYSBkb21hbmRhIGUnIHVuYSBzb2xhIHBlciB0dXR0aSBlIHRyZSBpIG1lc3RpZXJpIHVuaWNpLCBlCiAgICAgICBkaWNlIFFVQUxFIHN0YW56YS4gUHJpbWEgcXVlc3RhIHJpZ2Egbm9taW5hdmEgc29sbyBsYSBjYXNzYTogYSB1biDCq3NvbG8KICAgICAgIHBvc3RhemlvbmnCuyBsYSBsZW50ZSBvZmZyaXZhIGFuY29yYSDCq1Nwb3N0YSBvIHJpbXVvdmkgcHJvZG90dGnCuywKICAgICAgIMKrVHJhc2ZlcmlzY2kgbGUgc2NvcnRlwrssIMKrQWdnaXVuZ2kgcGl1JyBwcm9kb3R0acK7IGUgwqtDb250YXJlIHF1ZWxsbyBjaGUKICAgICAgIGMnZSfCuyDigJQgcGl1JyDCq1JlZ2lzdHJhcmUgbGEgbWVyY2UgYXJyaXZhdGHCuywgY2hlIGUnIGwndW5pY2Egdm9jZSBkZWdsaQogICAgICAgT3JkaW5pIHNlbnphIGBzZXJ2ZWAgZSBjYWRldmEgc3VsIHJpcGllZ28gZmluYWxlLiBUdXR0ZSBwb3J0ZSBzdWwgbXVyby4gKi8KICAgIGNvbnN0IHNvbG8gPSBtZXN0aWVyZVVuaWNvKHByb2ZpbG8pOwogICAgaWYgKHNvbG8pIHJldHVybiBhLmQgPT09IHNvbG87Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p019', substr((select value from kv_store where key='app:jsx:src'), 359194, 1100)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p020', convert_from(decode('ICAgICBNYWdhenppbmksIGUgdW4gY2Fzc2llcmUgbm9uIGhhIGRvbWFuZGUgZGkgbWFnYXp6aW5vIChnZW4tNi4xNykuCiAgICAg4pSA4pSAIE1BIE5PTiBBIENISSBDT05UQSAoZ2VuLTYuMjQpIOKUgOKUgAogICAgIEVzdGVuZGVyZSBxdWVzdGEgcmlnYSBhIHR1dHRpIGkgbWVzdGllcmkgdW5pY2kgc2VtYnJhdmEgc2ltbWV0cmljbywgZWQgZScKICAgICBzdGF0byBib2NjaWF0byBkYSB1bmEgTUlTVVJBOiBhIHVuIHByb2ZpbG8gwqtzb2xvIGNvbnRlZ2dpwrsgbGEgbGVudGUKICAgICByaXNwb25kZSDCq1BhdGF0ZSBmb3JubyDCtyBMaW5lYSBQaXp6ZSBmbSDCtyBwcmV2aXN0byAzIGduIMK3IDAgZ27CuywgY2lvZScgaWwKICAgICBtYWdhenppbm8sIGxhIHNvZ2xpYSBkZWwgZ2lvcm5vIGUgbGEgZ2lhY2VuemEuIFBlciB1biBjb250YXRvcmUgcXVlbGxhCiAgICAgbm9uIGUnIHVuYSBwb3J0YTogZScgaWwgbGF2b3JvLiBMYSByZWdvbGEgZXJhIHN0YXRhIHNjcml0dGEgcGVyIGlsCiAgICAgY2Fzc2llcmUsIGNoZSBkaSBtYWdhenppbm8gbm9uIGNoaWVkZSBuaWVudGUuIMKnMjRkIGUnIGlsIGd1YXJkaWFuby4gKi8KICBjb25zdCBzb2xvID0gbWVzdGllcmVVbmljbyhwcm9maWxvKTsKICBpZiAoc29sbyAmJiBzb2xvICE9PSAiY29udGVnZ2kiKSByZXR1cm4gW107Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p021', substr((select value from kv_store where key='app:jsx:src'), 360403, 102793)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p022', convert_from(decode('ICAgICAgLyog4pSA4pSAIEkgUklGRVJJTUVOVEkgU0kgRklMVFJBTk8gREVOVFJPIExBIEJPWlpBIChnZW4tNi4yNCkg4pSA4pSACiAgICAgICAgIFRyb3ZhdG8gZGVtb2xlbmRvOiBgZGF0aWAgc2kgY29zdHJ1aXNjZSBjb24gbG8gc3RhdG8gUmVhY3QgZm90b2dyYWZhdG8KICAgICAgICAgcXVhbmRvIGxhIHNjaGVkYSBzaSBlJyBhcGVydGEsIHF1aW5kaSBsYSByZWdvbGEgZGVsbGEgY2FzYSBlcmEKICAgICAgICAgcmlzcGV0dGF0YSBhIG1ldGEnIOKAlCBsJ0VOVElUQScgc2kgcmljZXJjYSBuZWxsYSBib3p6YSAoYHRyb3ZhKHMucHJvZmlsaSwKICAgICAgICAgaXRlbS5pZClgKSwgaSBzdW9pIFJJRkVSSU1FTlRJIG5vLiBEdWUgYWRtaW46IGlsIHByaW1vIGNhbmNlbGxhIGxhCiAgICAgICAgIHBvc3RhemlvbmUsIGlsIHNlY29uZG8gc2FsdmEgYW5jaGUgc29sbyBpbCBub21lIGRhIHVuYSBzY2hlZGEgYXBlcnRhCiAgICAgICAgIHByaW1hIGUgcmltZXR0ZSBkZW50cm8gbCdpZCBtb3J0bywgcGVyIHNlbXByZS4gUXVpIHNpIHRlbmdvbm8gc29sbyBnbGkKICAgICAgICAgaWQgY2hlIG5lbGxhIGJvenphIGVzaXN0b25vIGFuY29yYS4gKi8KICAgICAgY29uc3Qgdml2aSA9IChpZHMsIGxpc3RhKSA9PiAoaWRzIHx8IFtdKS5maWx0ZXIoKGlkKSA9PiAobGlzdGEgfHwgW10pLnNvbWUoKHgpID0+IHguaWQgPT09IGlkKSk7CiAgICAgIGNvbnN0IHBvc3RWaXZpID0gdml2aShwb3N0SWRzLCBzLnBvc3RhemlvbmkpOwogICAgICBjb25zdCBtYWdWaXZpID0gdml2aShtYWdJZHMsIHMubWFnYXp6aW5pKTsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p023', substr((select value from kv_store where key='app:jsx:src'), 463196, 128)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p024', convert_from(decode('ICAgICAgICBtYWdhenppbmlJZHM6IHJ1b2xvID09PSAib3BlcmF0b3JlIiA/IG1hZ1ZpdmkgOiB1bmRlZmluZWQsCg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p025', substr((select value from kv_store where key='app:jsx:src'), 463390, 127)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p026', convert_from(decode('ICAgICAgICBwb3N0YXppb25pSWRzOiBydW9sbyA9PT0gImFkbWluIiB8fCBwb3N0Vml2aS5sZW5ndGggPT09IDAgPyB1bmRlZmluZWQgOiBwb3N0Vml2aSwK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p027', substr((select value from kv_store where key='app:jsx:src'), 463605, 601)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p028', convert_from(decode('ICAgICAgICAvKiDilIDilIAgSUwgTUVTVElFUkUgTk9OIFNJIFNQRUdORSBQSVUnIERBIFNPTE8gKGdlbi02LjI0KSDilIDilIAKICAgICAgICAgICBQcmltYSBxdWVzdGUgZHVlIHJpZ2hlIHNwZWduZXZhbm8gaWwgbWVzdGllcmUgcXVhbmRvIGxhIGxpc3RhIGVyYQogICAgICAgICAgIHZ1b3RhLiBTZW1icmF2YSBpZ2llbmUgZWQgZXJhIGxhIGNvbnRyYWRkaXppb25lOiBzaWduaWZpY2F2YSBjaGUKICAgICAgICAgICBzdnVvdGFyZSB1bmEgbGlzdGEgUkVHQUxBVkEgYWwgcHJvZmlsbyB0dXR0ZSBsZSBzZXppb25pIGNoZSBuZXNzdW5vCiAgICAgICAgICAgZ2xpIGF2ZXZhIGFjY2Vzby4gQWRlc3NvIGlsIG1lc3RpZXJlIGUnIGRlbCBwcm9maWxvOyBzZSBsYSBsaXN0YSBzaQogICAgICAgICAgIHN2dW90YSwgbGEgc3VhIHN0YW56YSBnbGllbG8gZGljZS4gTG8gc3BlZ25lIFZhbGVyaW8sIGRhbCBzdW8KICAgICAgICAgICBpbnRlcnJ1dHRvcmUsIGNoZSBwZXIgcXVlc3RvIHF1aSBzb3R0byBub24gc2kgbmFzY29uZGUgcGl1Jy4gKi8KICAgICAgICBzb2xvUG9zdGF6aW9uaTogcnVvbG8gPT09ICJhZG1pbiIgPyB1bmRlZmluZWQgOiAoc29sb1Bvc3RpIHx8IHVuZGVmaW5lZCksCiAgICAgICAgc29sb0NvbnRlZ2dpOiBydW9sbyA9PT0gImFkbWluIiA/IHVuZGVmaW5lZCA6IChzb2xvQ29udCB8fCB1bmRlZmluZWQpLAo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p029', substr((select value from kv_store where key='app:jsx:src'), 464542, 931)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p030', convert_from(decode('ICAgICAgICAgICAgdmFsb3JlPXtzZWRlSWR9IG9uQ2FtYmlhPXsodikgPT4geyBzZXRTZWRlSWQodik7IHNldE1hZ0lkcyhbXSk7IHNldFBvc3RJZHMoW10pOyB9fSBvcHppb25pPXtzZWRpT2t9IC8+Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p031', substr((select value from kv_store where key='app:jsx:src'), 465572, 5963)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p032', convert_from(decode('ICAgICAgICAgICAgICBTaSBPRkZST05PIHNvbG8gcXVhbmRvIGMnZScgcXVhbGNvc2EgYSBjdWkgcmVzdGFyZSDigJQgbm9uIHNpCiAgICAgICAgICAgICAgcHJvcG9uZSB1biBtZXN0aWVyZSBzb3ByYSBpbCB2dW90byDigJQgbWEgc2Ugc29ubyBHSUEnIEFDQ0VTSSBzaQogICAgICAgICAgICAgIGRpc2VnbmFubyBzZW1wcmUgKGdlbi02LjI0KS4gUHJpbWEgc3Bhcml2YW5vIGluc2llbWUgYWxsJ3VsdGltYQogICAgICAgICAgICAgIHBvc3RhemlvbmU6IFZhbGVyaW8gbm9uIHZlZGV2YSBwaXUnIGwnaW50ZXJydXR0b3JlIGUgcXVpbmRpIG5vbgogICAgICAgICAgICAgIHBvdGV2YSBzcGVnbmVybG8sIG1lbnRyZSBpbCBwcm9maWxvIHJlc3RhdmEgbmVsIHN1byBtZXN0aWVyZS4gVW4KICAgICAgICAgICAgICBpbnRlcnJ1dHRvcmUgYWNjZXNvIGNoZSBub24gc2kgdmVkZSBlJyBpbCBtb2RvIHBpdScgcmFwaWRvIHBlcgogICAgICAgICAgICAgIHBlcmRlcmUgaWwgY29udHJvbGxvIGRpIGNvc2EgdmVkZSBsYSBwcm9wcmlhIGdlbnRlLiAqL30KICAgICAgICAgIHsocG9zdElkcy5sZW5ndGggPiAwIHx8IHNvbG9Qb3N0aSkgJiYgKAo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p033', substr((select value from kv_store where key='app:jsx:src'), 471838, 446)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p034', convert_from(decode('ICAgICAgICAgIHsobWFnSWRzLmxlbmd0aCA+IDAgfHwgc29sb0NvbnQpICYmICgK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p035', substr((select value from kv_store where key='app:jsx:src'), 472318, 321368)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p036', convert_from(decode('ICAgICAgICAvKiDilIDilIAgTEEgQ0FTQ0FUQSBDSEUgTUFOQ0FWQSAoZ2VuLTYuMjQpIOKUgOKUgAogICAgICAgICAgICBJbCBtYWdhenppbm8gY2UgbCdoYSBkYSBzZW1wcmUgKGVsaW1pbmFNYWdhenppbm9DYXNjYXRhKTsgbGEKICAgICAgICAgICAgcG9zdGF6aW9uZSBubywgZSBsJ2lkIHJlc3RhdmEgYXBwZXNvIG5laSBwcm9maWxpLiBFJyBJR0lFTkUsIG5vbgogICAgICAgICAgICBwZXJtZXNzaTogZGEgZ2VuLTYuMjQgaWwgbWVzdGllcmUgdW5pY28gbm9uIGd1YXJkYSBwaXUnIGxhCiAgICAgICAgICAgIGx1bmdoZXp6YSBkZWxsYSBsaXN0YSwgcXVpbmRpIHRvZ2xpZXJlIHVuIGlkIG1vcnRvIG5vbiBhY2NlbmRlIGUKICAgICAgICAgICAgbm9uIHNwZWduZSBuaWVudGUgYSBuZXNzdW5vIOKAlCBwcmltYSBpbnZlY2UgbCdhdnJlYmJlIGZhdHRvLCBlZCBlJwogICAgICAgICAgICBsYSBjb250cmFkZGl6aW9uZSBjaGUgaGEgdWNjaXNvIGlsIHByaW1vIGRpc2Vnbm8uCiAgICAgICAgICAgIEwnaWQgc2kgbGVnZ2UgZGFsbGEgY2xvc3VyZSBtYSBsYSBMSVNUQSBzaSByaXNjcml2ZSBkZW50cm8gbGEKICAgICAgICAgICAgYm96emEsIGUgaWwgZmlsdHJvIGUnIGlkZW1wb3RlbnRlOiByaWdpb2NhdG8gc3UgdW5hIGJvenphIGRvdmUKICAgICAgICAgICAgbCdpZCBub24gYydlJyBwaXUnIG5vbiBjYW1iaWEgbmllbnRlLiAqLwogICAgICAgIG9uU2k9eygpID0+IHsgbXV0YSgocykgPT4gewogICAgICAgICAgcy5wb3N0YXppb25pID0gKHMucG9zdGF6aW9uaSB8fCBbXSkuZmlsdGVyKCh4KSA9PiB4LmlkICE9PSBkZWxQb3N0LmlkKTsKICAgICAgICAgIGZvciAoY29uc3QgcHIgb2Ygcy5wcm9maWxpIHx8IFtdKSB7CiAgICAgICAgICAgIGlmICghKHByLnBvc3RhemlvbmlJZHMgfHwgW10pLmluY2x1ZGVzKGRlbFBvc3QuaWQpKSBjb250aW51ZTsKICAgICAgICAgICAgY29uc3QgcmVzdGEgPSBwci5wb3N0YXppb25pSWRzLmZpbHRlcigoeCkgPT4geCAhPT0gZGVsUG9zdC5pZCk7CiAgICAgICAgICAgIHByLnBvc3RhemlvbmlJZHMgPSByZXN0YS5sZW5ndGggPyByZXN0YSA6IHVuZGVmaW5lZDsKICAgICAgICAgIH0KICAgICAgICB9LCBgUG9zdGF6aW9uZSDCqyR7ZGVsUG9zdC5ub21lfcK7IHJpbW9zc2FgKTsgc2V0RGVsUG9zdChudWxsKTsgfX0gLz4K', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen624:p037', substr((select value from kv_store where key='app:jsx:src'), 793862, 269543)) on conflict (key) do update set value=excluded.value;

-- il cancello, PRIMA di scrivere
select md5(string_agg(value, '' order by key)) as md5_ricomposto,
       length(string_agg(value, '' order by key)) as len_ricomposto,
       md5(string_agg(value, '' order by key)) = 'cd1d92142ea7e891be2e35266859cb50' as combacia
from kv_store where key like 'tmp:gen624:p%';

update kv_store set value = (select string_agg(value, '' order by key) from kv_store where key like 'tmp:gen624:p%')
where key='app:jsx:src'
  and md5(value) = '3867679ff319995d9024e18abc4b2425'
  and (select md5(string_agg(value, '' order by key)) from kv_store where key like 'tmp:gen624:p%') = 'cd1d92142ea7e891be2e35266859cb50';

update kv_store set value = '{"len":1069982,"ver":"gen-6.24"}'
where key='app:jsx:meta'
  and (select md5(value) from kv_store where key='app:jsx:src') = 'cd1d92142ea7e891be2e35266859cb50';

delete from kv_store where key like 'tmp:gen624:p%';
