-- gen601: 17 zone cambiate, 35 tessere
-- 9f00b4a0a6629c664d659dac78052959 (840372) → 550f5b8b33f6e9414729b839e47686c3 (845589)

insert into kv_store(key, value) select 'backup:pre-gen601', value from kv_store where key='app:jsx:src'
  on conflict (key) do update set value=excluded.value;

insert into kv_store(key, value) values('tmp:gen601:p001', substr((select value from kv_store where key='app:jsx:src'), 1, 33985)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p002', convert_from(decode('Y29uc3QgVkVSU0lPTkUgPSAiZ2VuLTYuMDEiOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p003', substr((select value from kv_store where key='app:jsx:src'), 34015, 60126)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p004', convert_from(decode('ICAgIHsgdGl0b2xvOiAiTGEgdHVhIHBvc3RhemlvbmUiLCB0ZXN0bzogIkluIGFsdG8gc2NlZ2xpIGEgcXVhbGUgcG9zdGF6aW9uZSB0aSBzaWVkaSAoYW5jaGUgcGnDuSBkaSB1bmE6IGNoaSBmYSBpIGZyaXR0aSBzdGFzZXJhIHB1w7IgZmFyZSBhbmNoZSBpIGRvbGNpKS4gU2UgdW4gQWRtaW4gdGUgbmUgaGEgYXNzZWduYXRlIG5lbCBwcm9maWxvLCB1bm8gc2NoZXJtbyBudW92byBwYXJ0ZSBnacOgIGRhIHF1ZWxsZTsgYXBwZW5hIHRvY2NoaSBxdWkgY29tYW5kYSBxdWVzdG8gc2NoZXJtbywgZSDCq1Rvcm5hIGFsbGUgbWllIHBvc3RhemlvbmnCuyByaW1ldHRlIGxhIHNjZWx0YSBkZWwgcHJvZmlsby4gVmVkaSBzb2xvIGxlIHBvc3RhemlvbmkgZGVsbGEgdHVhIHNlZGUuIiB9LAo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p005', substr((select value from kv_store where key='app:jsx:src'), 94338, 313476)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p006', convert_from(decode('ICBjb25zdCBbcG9zdElkcywgc2V0UG9zdElkc10gPSB1c2VTdGF0ZShpdGVtPy5wb3N0YXppb25pSWRzIHx8IFtdKTsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p007', substr((select value from kv_store where key='app:jsx:src'), 407814, 505)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p008', convert_from(decode('ICBjb25zdCBjYW1iaWFSdW9sbyA9IChyKSA9PiB7IHNldFJ1b2xvKHIpOyBzZXRTZWRlSWQoIiIpOyBzZXRNYWdJZHMoW10pOyBzZXRQb3N0SWRzKFtdKTsgfTsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p009', substr((select value from kv_store where key='app:jsx:src'), 408396, 105)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p010', convert_from(decode('ICBjb25zdCB0b2dnbGVQb3N0ID0gKGlkKSA9PiBzZXRQb3N0SWRzKCh2KSA9PiAodi5pbmNsdWRlcyhpZCkgPyB2LmZpbHRlcigoeCkgPT4geCAhPT0gaWQpIDogWy4uLnYsIGlkXSkpOwogIC8qIGxlIHBvc3RhemlvbmkgYXNzZWduYWJpbGkgYSBxdWVzdG8gcHJvZmlsbzogcXVlbGxlIGRlbGxhIHN1YSBzZWRlIHBpdScKICAgICBxdWVsbGUgZGljaGlhcmF0ZSDCq3R1dHRlIGxlIHNlZGnCuy4gQXNzZWduYXJnbGkgbGEgcG9zdGF6aW9uZSBkaQogICAgIHVuJ0FMVFJBIHNlZGUgbm9uIHNlcnZpcmViYmU6IGxlIGNvbWFuZGUgZGkgcXVlbGxhIHNlZGUgbm9uIGdsaQogICAgIGFycml2ZXJlYmJlcm8gY29tdW5xdWUsIGlsIGZpbHRybyBkZWxsYSBzZWRlIHJlc3RhIHF1ZWxsbyBkaSBzZW1wcmUKICAgICAoZ2VuLTYuMDEsIGNoaWVzdG8gZGEgVmFsZXJpbzogwqtvZ25pIGNhc3NhIGRldmUgbWFuZGFyZSBsZSBjb21hbmRlCiAgICAgc29sbyBhbGxlIHBvc3RhemlvbmkgZGkgYXBwYXJ0ZW5lbnphwrspLiAqLwogIGNvbnN0IHBvc3RTZWRlID0gKHN0YXRvLnBvc3RhemlvbmkgfHwgW10pLmZpbHRlcigocG8pID0+ICFwby5zZWRlSWQgfHwgcG8uc2VkZUlkID09PSBzZWRlSWQpOwo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p011', substr((select value from kv_store where key='app:jsx:src'), 408501, 1301)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p012', convert_from(decode('ICAgICAgICAvKiBuaWVudGUgcGVyIGwnYWRtaW4gZSBuaWVudGUgcXVhbmRvIGUnIHZ1b3RvOiBpbCBjYW1wbyBhc3NlbnRlIGUnCiAgICAgICAgICAgaWwgdmVyc28gZ2l1c3RvIGFuY2hlIHF1aSAoZ2VuLTYuMDEpICovCiAgICAgICAgcG9zdGF6aW9uaUlkczogcnVvbG8gPT09ICJhZG1pbiIgfHwgcG9zdElkcy5sZW5ndGggPT09IDAgPyB1bmRlZmluZWQgOiBwb3N0SWRzLAo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p013', substr((select value from kv_store where key='app:jsx:src'), 409802, 2492)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p014', convert_from(decode('ICAgIHsvKiBMRSBQT1NUQVpJT05JIERFTCBQUk9GSUxPIChnZW4tNi4wMSkg4oCUIGNoaWVzdGUgZGEgVmFsZXJpbzogwqtub24gcG9zc28KICAgICAgICBhbmNvcmEgdmlzdWFsaXp6YXJlIGxlIHBvc3RhemlvbmkgbmVpIHByb2ZpbGkgbmVpIHF1YWxpIGxpIGFzc2Vnbm/Cuy4KICAgICAgICBTdGFubm8gUVVJLCBwcmltYSBlIEZVT1JJIGRhbCByaXF1YWRybyDCq0F1dG9yaXp6YXppb25pwrssIHBlcmNoZScgbm9uCiAgICAgICAgc29ubyB1biBwZXJtZXNzbzogbm9uIGFwcm9ubyBlIG5vbiBjaGl1ZG9ubyBuaWVudGUsIGRpY29ubyBzb2x0YW50bwogICAgICAgIMKrZGkgc29saXRvIHR1IHN0YWkgcXVpwrssIGUgc2Vydm9ubyBkYSBwdW50byBkaSBwYXJ0ZW56YSBhbGxvIHNjaGVybW8KICAgICAgICBjaGUgbm9uIGhhIGFuY29yYSBzY2VsdG8uICovfQogICAge3J1b2xvICE9PSAiYWRtaW4iICYmIHNlZGVJZCAmJiAoCiAgICAgIDxkaXY+CiAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJibG9jayB0ZXh0LXNtIGZvbnQtYm9sZCBtYi0xLjUiIHN0eWxlPXt7IGNvbG9yOiBULmluayB9fT5Qb3N0YXppb25pIGRpIGN1Y2luYTwvc3Bhbj4KICAgICAgICB7cG9zdFNlZGUubGVuZ3RoID09PSAwCiAgICAgICAgICA/IDxwIGNsYXNzTmFtZT0idGV4dC1zbSIgc3R5bGU9e3sgY29sb3I6IFQudGVudWUgfX0+CiAgICAgICAgICAgICAgUXVlc3RhIHNlZGUgbm9uIGhhIGFuY29yYSBwb3N0YXppb25pOiBsZSBkaXNlZ25hIHVuIEFkbWluIGRhIEdlc3Rpb25lIOKGkiBMaXN0aW5vLjwvcD4KICAgICAgICAgIDogPD4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImZsZXggZmxleC13cmFwIGdhcC0yIj4KICAgICAgICAgICAgICB7cG9zdFNlZGUubWFwKChwbykgPT4gewogICAgICAgICAgICAgICAgY29uc3Qgc2VsID0gcG9zdElkcy5pbmNsdWRlcyhwby5pZCk7CiAgICAgICAgICAgICAgICByZXR1cm4gKAogICAgICAgICAgICAgICAgICA8YnV0dG9uIGtleT17cG8uaWR9IG9uQ2xpY2s9eygpID0+IHRvZ2dsZVBvc3QocG8uaWQpfQogICAgICAgICAgICAgICAgICAgIGNsYXNzTmFtZT0icm91bmRlZC1mdWxsIHB4LTMuNSBweS0yIHRleHQtc20gZm9udC1ib2xkIGZsZXggaXRlbXMtY2VudGVyIGdhcC0xLjUiCiAgICAgICAgICAgICAgICAgICAgc3R5bGU9e3NlbAogICAgICAgICAgICAgICAgICAgICAgPyB7IGJhY2tncm91bmQ6IFQuYmx1LCBjb2xvcjogIiNmZmYiIH0KICAgICAgICAgICAgICAgICAgICAgIDogeyBiYWNrZ3JvdW5kOiAiI0YwRjNGQiIsIGNvbG9yOiBULmRpbSwgYm9yZGVyOiBgMXB4IHNvbGlkICR7VC5ib3Jkb31gIH19PgogICAgICAgICAgICAgICAgICAgIHtzZWwgJiYgPENoZWNrIHNpemU9ezEzfSAvPn17cG8ubm9tZX0KICAgICAgICAgICAgICAgICAgICB7IXBvLnNlZGVJZCAmJiA8c3BhbiBjbGFzc05hbWU9InRleHQteHMgZm9udC1zZW1pYm9sZCIgc3R5bGU9e3sgb3BhY2l0eTogLjc1IH19PsK3IHR1dHRlIGxlIHNlZGk8L3NwYW4+fQogICAgICAgICAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgICAgICAgICk7CiAgICAgICAgICAgICAgfSl9CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9ImJsb2NrIHRleHQteHMgbXQtMSIgc3R5bGU9e3sgY29sb3I6IFQudGVudWUgfX0+CiAgICAgICAgICAgICAgTm9uIMOoIHVuIHBlcm1lc3NvOiDDqCBpbCBwdW50byBkaSBwYXJ0ZW56YSBkZWxsbyBzY2hlcm1vIGNoZSBhcHJlIGxlIENvbWFuZGUuIENoaSBsYXZvcmEgcHXDsiBzZW1wcmUgY2FtYmlhcmUgc2VkaWEgZGFsIHN1byBzY2hlcm1vLjwvc3Bhbj4KICAgICAgICAgIDwvPn0KICAgICAgPC9kaXY+CiAgICApfQo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p015', substr((select value from kv_store where key='app:jsx:src'), 412294, 317186)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p016', convert_from(decode('ICAvKiBJTCBQUk9GSUxPIFBST1BPTkUsIElMIERJU1BPU0lUSVZPIENPTUFOREEgKGdlbi02LjAxKS4gTGEgc2VkaWEgcmVzdGEKICAgICBkZWwgRElTUE9TSVRJVk8g4oCUIGlsIHRhYmxldCBkaSBjdWNpbmEgZScgdW4gb2dnZXR0byBmaXNpY28gYXR0YWNjYXRvCiAgICAgYWxsYSBjb3JyZW50ZSBlIG5vbiBkZXZlIGNhbWJpYXJlIHBvc3RhemlvbmUgcGVyY2hlJyBhIG1ldGEnIHNlcnZpemlvCiAgICAgaGEgZmF0dG8gaWwgbG9naW4gdW4nYWx0cmEgcGVyc29uYS4gTWEgdW5vIHNjaGVybW8gY2hlIG5vbiBoYSBNQUkKICAgICBzY2VsdG8gKGNoaWF2ZSBhc3NlbnRlLCBub24gdnVvdGEpIHBhcnRlIGRhbGxlIHBvc3Rhemlvbmkgc2NyaXR0ZSBzdWwKICAgICBwcm9maWxvOiBjb3NpJyBpbCB0ZWxlZm9ubyBudW92byBkaSBjaGkgbGF2b3JhIGFwcmUgZ2lhJyBnaXVzdG8uCiAgICAgbnVsbCA9IG1haSBzY2VsdG87IHVuIGFycmF5IChhbmNoZSB2dW90bykgPSBpbCBkaXNwb3NpdGl2byBoYSBkZWNpc28uICovCiAgY29uc3QgW3NjZWx0YSwgc2V0U2NlbHRhXSA9IHVzZVN0YXRlKCgpID0+IHsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p017', substr((select value from kv_store where key='app:jsx:src'), 729527, 10)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p018', convert_from(decode('ICAgICAgY29uc3QgZ3JlenpvID0gbG9jYWxTdG9yYWdlLmdldEl0ZW0oInNjcDpjb21hbmRlOnYxIik7CiAgICAgIGlmIChncmV6em8gPT0gbnVsbCkgcmV0dXJuIG51bGw7CiAgICAgIGNvbnN0IHYgPSBKU09OLnBhcnNlKGdyZXp6byk7CiAgICAgIHJldHVybiBBcnJheS5pc0FycmF5KHYpID8gdiA6IG51bGw7CiAgICB9IGNhdGNoIHsgcmV0dXJuIG51bGw7IH0K', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p019', substr((select value from kv_store where key='app:jsx:src'), 729680, 6)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p020', convert_from(decode('ICBjb25zdCBzZWR1dGUgPSBzY2VsdGEgPT09IG51bGwgPyAocHJvZmlsby5wb3N0YXppb25pSWRzIHx8IFtdKSA6IHNjZWx0YTsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p021', substr((select value from kv_store where key='app:jsx:src'), 729686, 63)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p022', convert_from(decode('ICBjb25zdCBzaWVkaXRpID0gKGlkKSA9PiB7CiAgICBjb25zdCBkb3BvID0gc2VkdXRlLmluY2x1ZGVzKGlkKSA/IHNlZHV0ZS5maWx0ZXIoKHgpID0+IHggIT09IGlkKSA6IFsuLi5zZWR1dGUsIGlkXTsK', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p023', substr((select value from kv_store where key='app:jsx:src'), 729884, 83)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p024', convert_from(decode('ICAgIHNldFNjZWx0YShkb3BvKTsgICAvLyBkYWwgcHJpbW8gdG9jY28gaW4gcG9pIGNvbWFuZGEgcXVlc3RvIHNjaGVybW8KICB9OwogIGNvbnN0IHRvcm5hQWxQcm9maWxvID0gKCkgPT4gewogICAgdHJ5IHsgbG9jYWxTdG9yYWdlLnJlbW92ZUl0ZW0oInNjcDpjb21hbmRlOnYxIik7IH0gY2F0Y2gge30KICAgIHNldFNjZWx0YShudWxsKTsKICB9OwogIC8qIE9HTkkgQ0FTU0EgQUxMRSBTVUUgKGdlbi02LjAxLCBwYXJvbGUgZGkgVmFsZXJpbyk6IHF1ZXN0byBzY2hlcm1vIHB1bycKICAgICBzZWRlcnNpIHNvbG8gYWxsZSBwb3N0YXppb25pIGRlbGxhIFBST1BSSUEgc2VkZSwgcGl1JyBxdWVsbGUgZGljaGlhcmF0ZQogICAgIMKrdHV0dGUgbGUgc2VkacK7LiBPZmZyaXJlIGxhIHBvc3RhemlvbmUgZGkgdW4nYWx0cmEgc2VkZSBzYXJlYmJlIHVuYQogICAgIHBvcnRhIHN1IHVuYSBzdGFuemEgdnVvdGE6IGxlIGNvbWFuZGUgZGkgcXVlbGxhIHNlZGUgbm9uIGFycml2YW5vIHF1aQogICAgIGNvbXVucXVlLCBwZXJjaGUnIGlsIGZpbHRybyBkaSByZWNsYW1hbnRpKCkgZ3VhcmRhIGxhIHNlZGUgZGVsbGEKICAgICB2ZW5kaXRhLiBMJ2FkbWluIGxlIHZlZGUgdHV0dGUsIGNvbiBzY3JpdHRvIGRpIHF1YWxlIHNlZGUgc29uby4gKi8KICBjb25zdCBwb3N0YXppb25pUXVpID0gcHJvZmlsby5ydW9sbyA9PT0gImFkbWluIgogICAgPyBwb3N0YXppb25pCiAgICA6IHBvc3RhemlvbmkuZmlsdGVyKChwbykgPT4gIXBvLnNlZGVJZCB8fCBwby5zZWRlSWQgPT09IHByb2ZpbG8uc2VkZUlkKTsKICAvKiB1bmEgc2VkaWEgcHVvJyBwdW50YXJlIGEgdW5hIHBvc3RhemlvbmUgcmltb3NzYSAobyBkaSB1bidhbHRyYSBzZWRlLCBzZQogICAgIGlsIHByb2ZpbG8gZScgc3RhdG8gc3Bvc3RhdG8pOiBzaSBpZ25vcmEsIG5vbiBzaSByb21wZSAqLwogIGNvbnN0IG1pZSA9IG5ldyBTZXQoc2VkdXRlLmZpbHRlcigoaWQpID0+IHBvc3RhemlvbmlRdWkuc29tZSgocCkgPT4gcC5pZCA9PT0gaWQpKSk7Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p025', substr((select value from kv_store where key='app:jsx:src'), 730154, 2881)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p026', convert_from(decode('ICAgICAge3Bvc3RhemlvbmlRdWkubGVuZ3RoID09PSAwCg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p027', substr((select value from kv_store where key='app:jsx:src'), 733066, 471)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p028', convert_from(decode('ICAgICAgICAgICAgICB7cG9zdGF6aW9uaVF1aS5tYXAoKHBvKSA9PiB7IGNvbnN0IGdpdSA9IG1pZS5oYXMocG8uaWQpOyByZXR1cm4gKAo=', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p029', substr((select value from kv_store where key='app:jsx:src'), 733614, 427)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p030', convert_from(decode('ICAgICAgICAgICAgICAgICAge3Byb2ZpbG8ucnVvbG8gPT09ICJhZG1pbiIgJiYgcG8uc2VkZUlkICYmICgKICAgICAgICAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InRleHQteHMgZm9udC1zZW1pYm9sZCIgc3R5bGU9e3sgb3BhY2l0eTogLjc1IH19PgogICAgICAgICAgICAgICAgICAgICAgwrcge3Ryb3ZhKHN0YXRvLnNlZGksIHBvLnNlZGVJZCk/Lm5vbWUgfHwgInNlZGUifTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgKX0K', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p031', substr((select value from kv_store where key='app:jsx:src'), 734041, 66)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p032', convert_from(decode('ICAgICAgICAgICAgey8qIGxhIHZpYSBkZWwgcml0b3JubzogY2FuY2VsbGEgbGEgc2NlbHRhIGRpIFFVRVNUTyBzY2hlcm1vIGUKICAgICAgICAgICAgICAgIHJpbWV0dGUgcXVlbGxhIHNjcml0dGEgc3VsIHByb2ZpbG8gKGdlbi02LjAxKSAqL30KICAgICAgICAgICAge3NjZWx0YSAhPT0gbnVsbCAmJiAocHJvZmlsby5wb3N0YXppb25pSWRzIHx8IFtdKS5sZW5ndGggPiAwICYmICgKICAgICAgICAgICAgICA8YnV0dG9uIG9uQ2xpY2s9e3Rvcm5hQWxQcm9maWxvfQogICAgICAgICAgICAgICAgY2xhc3NOYW1lPSJ0ZXh0LXhzIGZvbnQtYm9sZCBtdC0yIHJvdW5kZWQtZnVsbCBweC0zLjUiCiAgICAgICAgICAgICAgICBzdHlsZT17eyBjb2xvcjogVC5ibHUsIGJhY2tncm91bmQ6ICIjRUFGMEZFIiwgbWluSGVpZ2h0OiAzNiB9fT5Ub3JuYSBhbGxlIG1pZSBwb3N0YXppb25pPC9idXR0b24+CiAgICAgICAgICAgICl9Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p033', substr((select value from kv_store where key='app:jsx:src'), 734107, 144)) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p034', convert_from(decode('ICAgICAgICAgICAgICAgIHRlc3RvPSJUb2NjYSBxdWkgc29wcmEgbGEgcG9zdGF6aW9uZSBkaSBjdWkgdGkgb2NjdXBpIOKAlCBhbmNoZSBwacO5IGRpIHVuYTogY2hpIGZhIGkgZnJpdHRpIHN0YXNlcmEgcHXDsiBmYXJlIGFuY2hlIGkgZG9sY2kuIExhIHNjZWx0YSByZXN0YSBzdSBxdWVzdG8gc2NoZXJtbzsgc2UgdW4gQWRtaW4gdGUgbmUgaGEgYXNzZWduYXRlIG5lbCBwcm9maWxvLCDCq1Rvcm5hIGFsbGUgbWllIHBvc3RhemlvbmnCuyByaW1ldHRlIHF1ZWxsZS4iIC8+PC9TY2hlZGE+Cg==', 'base64'), 'UTF8')) on conflict (key) do update set value=excluded.value;
insert into kv_store(key, value) values('tmp:gen601:p035', substr((select value from kv_store where key='app:jsx:src'), 734441, 105932)) on conflict (key) do update set value=excluded.value;

-- il cancello, PRIMA di scrivere
select md5(string_agg(value, '' order by key)) as md5_ricomposto,
       length(string_agg(value, '' order by key)) as len_ricomposto,
       md5(string_agg(value, '' order by key)) = '550f5b8b33f6e9414729b839e47686c3' as combacia
from kv_store where key like 'tmp:gen601:p%';

update kv_store set value = (select string_agg(value, '' order by key) from kv_store where key like 'tmp:gen601:p%')
where key='app:jsx:src'
  and md5(value) = '9f00b4a0a6629c664d659dac78052959'
  and (select md5(string_agg(value, '' order by key)) from kv_store where key like 'tmp:gen601:p%') = '550f5b8b33f6e9414729b839e47686c3';

update kv_store set value = '{"len":845589,"ver":"gen-6.01"}'
where key='app:jsx:meta'
  and (select md5(value) from kv_store where key='app:jsx:src') = '550f5b8b33f6e9414729b839e47686c3';

delete from kv_store where key like 'tmp:gen601:p%';
